- README.md
Piping is a little simpler than mounting a volume and also works well
for those running docker in a virtual machine.
> Fix README to reference piping to docker

- src/Normalize.hs
- src/Test.hs
Most escaping problems should be resolved without code for each rule.
> Handle multiline bash escape as preparation step

- hadolint.cabal
optparse-applicative: restrict to <0.13.0.0
Until hadolint has support for optparse-applicative >=0.13.0,
restricting it to <0.13.0.0 prevents build failure with errors such as
app/Main.hs:31:32: error:
```
• Variable not in scope: (<>) :: Mod f0 a0 -> Mod f1 a1 -> t0
• Perhaps you meant one of these:
‘<$>’ (imported from Options.Applicative),
‘<*>’ (imported from Options.Applicative),
‘>>’ (imported from Prelude)
```
> optparse-applicative: restrict to <0.13.0.0

- src/Hadolint/Rules.hs
- test/Spec.hs
Addresses #59.
* I'm not sure how the numbering is decided for the rules so I just went with `DL4005` because it was the first number available after the highest `DL` number.
* There might be a better way to detect this shell symlinking behavior but right now I just assert that the `RUN` command is using `ln` and one of the arguments is `/bin/sh`. Open to suggestions for how to do this better. I'm not sure if this behaves well with chained commands for example (like `ln -s foo bar && something_with /bin/sh`)
* This doesn't handle anything for windows users. Noting this given that the docker reference recommends the `SHELL` instruction for windows users who prefix everything with `powershell -command ...`
> Add "use SHELL" rule for ln with /bin/sh

- src/Hadolint/Lexer.hs
- src/Hadolint/Parser.hs
- src/Hadolint/Syntax.hs
- test/Spec.hs
Just plain parse HEALTHCHECK (not even correctly) so people won't experience parser failures.
Resolves #62.
> Parse HEALTHCHECK 

- app/Main.hs
- src/Hadolint/Formatter.hs
- test/Spec.hs
Resolves #57.
Now looks like this when parse error happens:
```
Dockerfile:3:1 unexpected 'B' expecting space, "\t", "ONBUILD", "FROM", "COPY", "RUN", "WORKDIR", "ENTRYPOINT", "VOLUME", "EXPOSE", "ENV", "ARG", "USER", "LABEL", "STOPSIGNAL", "CMD", "SHELL", "MAINTAINER", "ADD", "#" or end of input
```
Instead of
```
"/tmp/Dockerfile634358372" (line 1, column 5):
unexpected 'S'
expecting end of "CMD"
```
> Unified error formatting 

- app/Main.hs
Calling `exitFailure` is useful when invoking `hadolint` in a script before building an image with a malformed Dockerfile; we can prevent a potentially time-consuming but ultimately doomed build this way.
Furthermore, calling `exitFailure` if no Dockerfile has been given provides better feedback to the user (or calling script) that `hadolint` has been misused.
References #95
> Call exitFailure if Dockerfile cannot be parsed or one is not provided

- .dockerignore
- .gitignore
- .travis.yml
- Dockerfile
- app/Main.hs
- hadolint.cabal
- src/Hadolint/Bash.hs
- stack.yaml
- Update GHC to `lts-9.10` and base image to Debian `stretch` as `jessie` (used in haskell image) is no longer supported
- Support a new version of `ShellCheck` (0.4.6+)
- Build hadolint as a static binary
```
--ghc-options '-optl-static -fPIC -optc-Os -optl-pthread'
```
- Compress it with `upx`
```
Ultimate Packer for eXecutables
Copyright (C) 1996 - 2013
UPX 3.91        Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 30th 2013
File size         Ratio      Format      Name
--------------------   ------   -----------   -----------
17335248 ->   2345924   13.53%  linux/ElfAMD   hadolint
```
- Use multistage docker build to be able to get minimal size image (4.39 MB) [zemanlx/hadolint](https://hub.docker.com/r/zemanlx/hadolint/)
- Add version number from `git describe` (a tag has to be …
> Update dependencies + multistage docker image + version from git

- Dockerfile
so Travis won't fail on timeout.
Previously it took 1167 s, now 841 s to build docker container in Travis.
> Use the new UPX which is much faster

- src/Hadolint/Rules.hs
- test/Spec.hs
Add support for `pip install` arguments `--user` and `--disable-pip-version-check` without breaking pip packages version pinning + some tests to `Spec.hs`.
Resolves @agounaris and @zemanlx requests from https://github.com/lukasmartinelli/hadolint/issues/67
> Support for pip install arguments --user and --disable-pip-version-check

- Dockerfile
- scripts/fetch_version.sh
The shallow clone is used in Docker Hub automated build, therefore we missing version number there and not in Travis where clone has `depth=50`.
Resolve #105.
> Fetch tags and last 100 commits to get a version for shallow clone

- src/Hadolint/Rules.hs
- test/Spec.hs
Multistage build added optional names for images, which can be used later within Dockerfile.
```Dockerfile
FROM <image> [AS <name>]
```
or
```Dockerfile
FROM <image>[:<tag>] [AS <name>]
```
or
```Dockerfile
FROM <image>[@<digest>] [AS <name>]
```
This PR fixes #108 by checking not only `latest` but also `latest as` or `latest AS`. I have also added tests to `Spec.hs`
https://docs.docker.com/engine/reference/builder/#from
> Add checks for `latest` as tag for named image

- src/Hadolint/Rules.hs
- test/Spec.hs
This PR fixes #109 by checking that user is not only `root` by also `root:*` or `0` (root's user id) or `0:*` as `USER` can be defined as 
```Dockerfile
USER <user>[:<group>]
```
or
```Dockerfile
USER <UID>[:<GID>]
```
https://docs.docker.com/engine/reference/builder/#user
> Check for root defined as UID 0 or root with group

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
Pinning supports various formats
```bash
npm install (with no args, in package dir)
npm install [<@scope>/]<name>
npm install [<@scope>/]<name>@<tag>
npm install [<@scope>/]<name>@<version>
npm install git[+http|+https]://<git-host>/<git-user>/<repo-name>[#<commit>|#semver:<semver>]
npm install git+ssh://<git-host>:<git-user>/<repo-name>[#<commit>|#semver:<semver>]
```
and one flag `--global`.
I have also added wiki page for [DL3016](https://github.com/lukasmartinelli/hadolint/wiki/DL3016)
Fixes #3.
> npm version pinning

- src/Hadolint/Rules.hs
- test/Spec.hs
`pip install` version pinning should not fail if user does not want to use local cache in Dockerfile, therefore this PR will accept [`--no-cache-dir`](https://pip.pypa.io/en/stable/reference/pip_install/#caching) as an option.
Fixes #115.
> Accept `--no-cache-dir` option in `pip install`

- .travis.yml
- appveyor.yml
- docs/RELEASE.md
1. Use GitHub Releases deployment feature to upload binaries for each release automatically. 
2. For making binaries as small as possible (for frequent download in CI environment) I have added `upx` compression for tagged/release builds for all 3 OS we support.
There are a few more minor changes included in this PR: 
- Name binaries hadolint-OS-ARCH.
- Use choco for stack install in AppVeyor.
- Use caching in AppVeyor.
- Sync Travis and AppVeyor stack commands as much as possible.
- Lint Travis and AppVeyor YAML files.
I have also added document how to make a release smooth with GitHub.
I have tested it in my fork
- Release builds in [Travis](https://travis-ci.org/zemanlx/hadolint/builds/304071070) and [AppVeyor](https://ci.appveyor.com/project/zemanlx/hadolint/build/1.0.99)
- Release …
> Add support for upx and new support for GitHub releases

- .dockerignore
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- README.md
- appveyor.yml
- docker/Dockerfile
- docker/README.md
- docker/hooks/build
- docker/hooks/push
- docs/RELEASE.md
- hadolint.cabal
- scripts/fetch_version.sh
- src/Hadolint/Rules.hs
- Replaced `lukasmartinelli` username by `hadolint` organisation in all documents and source code.
- Commented reference to http://hadolint.lukasmartinelli.ch/ as it is not working for some time. Happy to uncomment when @lukasmartinelli fix it.
- Linted all markdown files.
- Moved `Dockerfile` to `docker` folder with `README.md` for Docker Hub/Store and setup build hooks
that will add extra tags to the image. See [README](https://github.com/zemanlx/hadolint/blob/ca864fb2f4ae1e20012c1be9580790cd65a4a2af/docker/README.md) for Docker Hub.
- Updated (security) `curl` package.
Fixes #121.
Numerous tests on my own fork. Unfortunately, all new features and fixes for old bugs of Docker Hub are deployed only to Docker Cloud what complicates a bit how images can be built. Hub and Cloud share the …
> Transfer from lukasmartinelli to organisation

- .dockerignore
- docker/README.md
- docker/hooks/push
I have found out that Docker Hub actually use hooks and with a bit of hacking it also serves the build context and README in a right way. What is different compared to Docker Cloud is that it get a shallow clone of repo. 
Even though Docker prefer to use of Docker Cloud, build status log and information are taken from Docker Hub even those that are shown on Docker Store :disappointed: 
- Get unshallow clone to get a version
- Remove unnecessary tags and options from commands
- Change markdown to long lines
See my fork's docker hub [zemanlx/hadolint](https://hub.docker.com/r/zemanlx/hadolint/)
> Tune for Docker Hub

- src/Hadolint/Parser.hs
- test/Spec.hs
Fixes #50 
Drop whitespace characters between non-quoted key and value in `Parser`'s `pair`.
There is a test for this in `Spec.hs`
> Drop whitespace characters between non-quoted key and value

- README.md
Update `README.md` to reflect change to DL4000 rule.
N/A.
N/A.
> DL4000 now enforces deprecation of MAINTAINER

- appveyor.yml
Changed AppVeyor GitHub Releases key
Old one was for lukasmartinelli personal hadolint, new one is for project hadolint https://ci.appveyor.com/project/hadolint/hadolint
Generated new token and encrypted it in https://ci.appveyor.com/tools/encrypt
Will test with next version rc.
> Change AppVeyor GitHub Releases key

- src/Hadolint/Rules.hs
- test/Spec.hs
Added `-qq` option as alternative to `-y` in `apt-get`.
Note that quiet level 2 implies -y.
> man apt-get
Fixes #131.
Added `-qq` as accepted option to `aptGetPackages` and as an alternative to `-y` in `aptGetYes`.
There is a test for it.
> Add `-qq` option as alternative to `-y` in `apt-get`

- src/Hadolint/Rules.hs
Lower severity for using `root`.
Closes #29.
> Lower severity for using root

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
Added support for [alpine](https://alpinelinux.org/) `apk` package tool that should be similar to what we have for debian/ubuntu `apt-get`. As a bonus, I have added support for virtual packages so version pinning won't fail because of that.
I have added rules
- Do not use `apk upgrade`. https://github.com/hadolint/hadolint/wiki/DL3017
- Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`. https://github.com/hadolint/hadolint/wiki/DL3018
- Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages. https://github.com/hadolint/hadolint/wiki/DL3019
Closes #132. 
- Do not use `apk upgrade` - check if  `apk upgrade`  is part of args  of `RUN` instruction
- Pin versions in apk add. Instead of …
> Version pinning for alpine apk

- docs/INTEGRATION.md
- docs/RELEASE.md
- hadolint.cabal
- Added Alpine `apk` support #134
- Added support for `-qq` option in `apt-get` #138
- Added fallback version if binary is compiled without git (`brew` installation) #136
- Added Hadolint Integrations page for Travis and editors #129 
- Improvements in the project README thanks to @proinsias #130 and @samiralajmovic #128
- Fixed _ENV parameters separated by multiple spaces causing parse error_ #50 in #127 
- Seperated parsing and used the `language-docker` package
- Used new `lts-9.18 `stack
- Linted all haskell fles using hindent
> Release 1.2.4 preparation

- hadolint.cabal
- src/Hadolint/Bash.hs
- stack.yaml
Upgraded ShellCheck to 0.4.7 which is adding `--check-sourced` option and changing the type of [CheckSpec](https://github.com/koalaman/shellcheck/commit/8dd40efb440db9ad189ed49695550596ed20100b#diff-6369a4e9c22ed3b4605c0454805c6e5fR36) to support it.
Fixes #143.
The new version is not in LTS stack, therefore, I have had to specify it explicitly in `stack.yaml`. I have set `sourced` to `False` as this is default in ShellCheck and we are not sourcing.
`stack test` as usual.
> Upgrade ShellCheck to 0.4.7

- README.md
Fix this 
| Rule                                                         | Description                                                                                                                                         |
|--------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------|
| [SC2002](https://github.com/koalaman/shellcheck/wiki/SC2002) | Useless cat. Consider `cmd < file | ..` or `cmd file | ..` instead.    |
to this
| Rule                                                         | Description …
> Fix broken messages in the README table

- .remarkrc.yaml
- .travis.yml
- README.md
- docker/.remarkrc.yaml
- docs/INTEGRATION.md
- docs/RELEASE.md
- package.yaml
- stack.yaml
New build in Travis will check for Haskell (hlint) and Markdown (remark) linting issues. I have also added a check if a version in `package.yaml` is equal or higher than a version in `git describe` to avoid situation when we forgot to update a version number in `package.yaml` before release. This, of course, won't stop us to do it, but at least alerts us when we forgot.
Out of scope changes:
- removed docker update - no longer needed for a multistage build. Travis is now using `17.09-ce` by default. It saves us some time.
- update to LTS-10.7 and removed optparse-applicative restriction. I have never seen it failing because of any new version of that package. 
Travis baby.
> Linting and version check

- src/Hadolint/Rules.hs
- test/Spec.hs
Hadolint will no longer complain about violation of  [DL3013](https://github.com/hadolint/hadolint/wiki/DL3013) for `pip install .`
Closes #88.
Added a new function to check that check that `.` is part of `pip install` command. Hope that will not easy other checks as soon as `.` cannot be part of any package name.
Simplified a logic in the check.
I have added test for it and old ones are not failing.
> Add support for "pip install ."

- src/Hadolint/Rules.hs
Removing full stop from rules message for consistency.
> Remove full stop "." from messages

- src/Hadolint/Rules.hs
- test/Spec.hs
to be able to tolerate "target-release" option.
Ignore `--target-release` and `-t` in `apt-get`.
Fixes #177.
Use `dropOptionsWithArg` for `apt-get` to be able to tolerate `--target-release` option. It is used for `apk add` already.
I have added a test.
> Use dropOptionsWithArg for apt-get

- src/Hadolint/Rules.hs
- test/Spec.hs
fixes #181 
Re-implemented how `pip install` and `npm install` packages are found, by not hardcoding as much as before.
Added a new test case
> Fixed the way pip and npm packages are found in RUN instructions

- docs/INTEGRATION.md
Add a example to use hadolint Docker container with Gitlab CI.
By adding a new section to the integration manual :-)
Add the job mentioned to any .gitlab-ci.yml configuration in a project where a Dockerfile exists
> add Gitlab CI example

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixes #188
Modified aptGetPackages to treat any word in the command that starts with a "-" as an option.
Existing test case modified to include squished option "-yqq".
> Permit squishing of single-letter options to apt-get install

- docker/Dockerfile
- package.yaml
- src/Hadolint/Formatter/Checkstyle.hs
- src/Hadolint/Formatter/Codeclimate.hs
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Formatter/TTY.hs
- src/Hadolint/Rules.hs
- test/Spec.hs
There were certain rules that were not reporting the line number where we detected the failure. Most of them were checking duplicated "stuff" across different rules. I made a change so that all but the first place where we detect a duplicate are reported as faulty.
fixes #201
> Fix rules reporting -1 as line number

- package.yaml
- stack.yaml
A new version of ShellCheck has been released last week so update to keep us :sunglasses:
> Update ShellCheck to 0.5.0

- docker/Dockerfile
- docker/README.md
#205 solved our issue with UTF characters so we can go back to minimal size image.
```bash
echo -e "FROM scratch\nLABEL nasty=مقرف讨厌противныйน่ารังเกียจ\n" > Dockerfile.utf
docker build --tag hadolint:$(git describe --tags --dirty) --file docker/Dockerfile .
docker run --rm -i hadolint:$(git describe --tags --dirty) < Dockerfile.utf
```
> Use scratch as base image for distro

- .travis.yml
Fixes #173 
When `LC_ALL` is set during compilation it causes that binary is crashing as described in #173 (in case `LC_ALL` is not set on end machine).
> Using LC_ALL is strongly discouraged as it overrides everything. Please use it only when testing and never set it in a startup file.
https://wiki.debian.org/Locale
Tested release binaries 1.5.0 and 1.7.0 in Debian Buster with locale as described in #173 and they were crashing. Then I mounted my locally build binary with `LC_ALL` set to "" and that one works :tada:
> Set `LC_ALL=` for Travis

- .travis.yml
Forced `stack` and `hadolint` to use `LC_ALL=` during compilation and test.
I think that Travis is setting `LC_ALL` in `.bashrc` which is overwriting what is set in global env.
Fixes #173 
Prepend `LC_ALL=` to all commands that matter.
I hope that `LC_ALL= hadolint docker/Dockerfile` in Travis does the trick.
> Set LC_ALL to empty before build & test

- .travis.yml
Yet another experiment to fix #173. This time I was able to reproduce issue from Travis in ubuntu:14.04 docker image, and solve it by switching to 16.04. 
Just for evidence, I have tried all combination of `LC_*` with different versions of `gcc` an `clang` without any success. 
Merge it and then run artifact from master branch of Travis second build in Debian Buster
```bash
$ docker run --rm -it -w /test debian:buster bash
```
and then in a container
```bash
apt update && apt install wget locales
echo "en_US.UTF-8" >> /etc/locale.gen
locale-gen
export LANG=en_US.UTF-8
export LANGUAGE=
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export …
```
> Build in Ubuntu 16.04 (xenial)

- package.yaml
- src/Hadolint/Bash.hs
- src/Hadolint/Rules.hs
- test/Spec.hs
Implementing our own shell parser based on splititng on whitespace was
brittle, specially in the parsing of `RUN` instructions with multiple
commands.
This change introduces several new functions to inspect the ShellCheck AST
and perform both transformations and assertions to all the scripts we find
in a dockerfile
I also took the chance to fix #216 in the process
Funnily enough, this also fixes #217
> Used the ShellCheck AST to perform bash assertions

- docker/Dockerfile
- docker/README.md
- docs/INTEGRATION.md
- Updated version in docs
- Changed base image for Debian distro image to use same as we have for build. That should shorten a build time as we do not need to download another image.
> Update version in docs & unify base image

- src/Hadolint/Rules.hs
- test/Spec.hs
The `shellcheckBash` rule was the last rule to not use one of the instruction traversal functions, which caused it to not inherit the automatic traversal of `ONBUILD` instructions.
I had to change a bit how the traversal functions worked, since `shellcheck` can produce many messages per instruction, which we were not prepared to do.
Fixes #230
> Make sure shellcheck runs in ONBUILD

- app/Main.hs
- package.yaml
- src/Hadolint/Rules.hs
- stack.yaml
- test/Spec.hs
This implements and closes #225 
The CLI now accepts many `--trusted-registry` flags and a new config file key `trustedRegistries` to control what registries can be used in `FROM` instructions.
Example:
`hadolint --trusted-registry crazy.io --trusted-registry random.io Dockerfile`
> Warn on untrusted FROM registries

- package.yaml
- src/Hadolint/Rules.hs
- test/Spec.hs
It was failing when using a stage as an image name
> Fixed the Allowed registries rule

- README.md
Fixed some typos! Notably:
```
As shwon before, hadolint ia
```
=>
```
As shown before, `hadolint` is
```
In English. And `vim`.
Grammar.
-----------
- Standardized styling of `hadolint` references (i.e., wrapped in `backticks` whenever in prose).
- Standardized references to other proper nouns (Docker, Debian) as capitalized.
> [docs] Fix typos in README.

- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- test/Spec.hs
When the shell is set to powershell, we avoid running shellcheck
and the pipefail check.
fixes #246
> Avoid running certain rules with powershell

- src/Hadolint/Rules.hs
- test/Spec.hs
No longer warn about missing constraints for pip packages when the flag
is present.
fixes #229
> Added support for the --constraint flag in pip

- app/Main.hs
- src/Hadolint/Formatter/Codacy.hs
Hey guys,
First of all, we really like the tool you’ve created, and we would love to support it on our product.
Because of this, we needed a formatter that would return an output matching the one we expect on our side, so we created one (Codacy.hs) similarly to the ones you already have on your tool and added it as an option to your Main.hs.
Let us know if something needs improvement.
Epic Code Reviews
> Add codacy formatter

- docs/INTEGRATION.md
Thank you for the great tool!
I am adding Codacy to the integration page as an automated code review tool.
This way, more people can use hadolint analysis out of the box, for free.
> Add Codacy to integrations page

- package.yaml
- src/Hadolint/Lint.hs
- src/Hadolint/Rules.hs
- stack.yaml
No longer using /dev/stdin as the pseudo file for parsing stdin.
Instead, read stdin directly.
fixes #273 
fixes #263
> Upgrading parser to verion 7

- .travis.yml
- package.yaml
- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- stack.yaml
- test/Spec.hs
- Updated SheckCheck from 0.5.0 to 0.6.0
- ￼Add allowed `repository` flag for `apk add` - fixes #290
- ￼Add allowed `index-url` falgs for `pip install` - fixes #287
- Updated stack to latest `lts` and fixed all issues that raised as `ShellCheck.Interface` was heavily refactored.
Travis-CI should now pass for all environments, even `nightly`. For fixes, I have added tests.
> Update ShellCheck to 0.6.0

- src/Hadolint/Rules.hs
- test/Spec.hs
closes #318 
added a `noApt` rule to detect and discourage use of `apt`, recommending `apt-get` or other binaries
Followed the pattern of `noSudo`
Simple test is included
> Add noApt rule

- src/Hadolint/Rules.hs
- test/Spec.hs
add gem version pinning (to match pip, npm)
detect `gem install|i PACKAGE:VERSION`
Tests included
> Add gem version pinning

- src/Hadolint/Shell.hs
According to https://github.com/koalaman/shellcheck/wiki/SC1090 the fix is to put a shell comment "directive" to assist -- "# shellcheck source=/dev/null".  This can't work in a Dockerfile because `#` is also the Docker comment character.  So with no obvious workaround, the error must simply be ignored completely.
* fixes #343
> Ignore unsatisfiable shellcheck error 1090

- src/Hadolint/Rules.hs
- test/Spec.hs
When using the long parameter for installing pip packages (`RUN pip install --requirement /tmp/requirements.txt`), this get's incorrectly reported by hadolint as un-pinned package versions, as hadolint currently only recognizes the short parameter (`RUN pip install -r /tmp/requirements.txt`).
This PR extends the parsing rules so that also the long parameter is recognized properly.
When having a `RUN pip install --requirement /tmp/requirements.txt
` statement in the Dockerfile, previously hadolint reported:
```
Dockerfile:4 DL3013 Pin versions in pip. Instead of `pip install <package>` use `pip install <package>==<version>`
```
With the changed version, it correctly recognizes it as an installation of pinned package versions.
> Support pip requirement pinning with long parameter

- docs/INTEGRATION.md
I added a section to the integration documentation that describes how to include hadolint as a linter into Geany's build system.
I copied and pasted the relevant code from configuration.  Specifically, the code kicks off a Docker container with hadolint/hadolint then massages the output with sed into a format that Geany interprets as an error location.  If the output includes a string (in this case, ':WARNING:') then the build (lint) is marked as having failed.
Geany's build system runs the command via `/bin/sh -c ' (stuff) '` with quotes escaped and the following replacements:
%d directory to the file being edited / run
%f filename (basename -- no directory)
Screenshot:
Open a Dockerfile, include the code in Geany's build actions, and run it.
> Geany integration

- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- test/Spec.hs
Fixes false positive when suplying a gem version via the `--version` flag:
```
RUN gem install bundler --version '2.0.1'
RUN gem install bundler --version='2.0.1'
```
While I was able to make it work for the `--version '2.0.1'` case, I don't know what to do to make it work for `--version='2.0.1'` (with the `=` in between).
I've added tests for both cases.
closes #336
> Fix gem version check when suplying the `--version` flag

- docs/INTEGRATION.md
The YAML in the current docs fails with: 
> Found errors in your .gitlab-ci.yml:
>
> lint_dockerfile job: stage parameter should be:
>  - .pre
>  - build
>  - test
>  - deploy
>  - .post
>
> You can also test your .gitlab-ci.yml in CI Lint
This fixes that (though it might put the linting into the wrong phase)
Docpatch
1. Paste the previous version into a `.gitlab-ci.yaml`, get 🔴 _your YAML is invalid_
1. Paste this version into a `.gitlab-ci.yaml`, get 💚 _the results of a lint_
> INTEGRATION.md: gitlab-ci

- .travis.yml
- README.md
- docker/Dockerfile
- docker/README.md
- docker/hooks/build
- docker/hooks/push
I've added an alpine target image, updating travis and documentation stuff where necessary. This come after some weeks of tests in my company where we need to use hadolint on jenkins' k8s plugin and we use alpine for the sake of image size (~8MiB vs debian's 53). We'd be glad if you consider adopting this enhancement.
Updated READMEs, travis config, dockerfile and his hooks. I didn't touched INTEGRATION docs because I'm unsure on how to proceed w/o rendering that file too much "noisy", what do you think about?
Pipelines should pass
HTH, ciao!
> alpine image

- docs/INTEGRATION.md
GitHub Actions use a YAML workflow definition now, so this updates the integration example doc to reflect the new syntax.
Lots of trial and error to get Hadolint running in Actions😸 
Create a PR adding the contents of the example action to `.github/workflows/main.yml`
> update actions syntax

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixed #345.
Allowed packages containing `/` (is defined by path is OS) and have the suffix `.deb` to be considered versioned.
Added tests.
> Allow installation from deb file as versioned

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixed #356.
Looked at [docs](https://docs.npmjs.com/cli/install) and implemented tarball installation based on list of suffixes and folder installation based on prefixes with `/`.
I do not think that we can detect if users are installing from a folder or they are installing an unversioned package
```bash
npm install folder_or_package_who_knows
```   
This will be a false positive if it is a folder.
I have written tests to cover cases I can think of.
> Allow npm local install

- docs/INTEGRATION.md
Fixed the INTEGRATION docs for CircleCI. The `dockerfile:` key was renamed to `dockerfiles:` and the example made to illustrate it supports a comma-separated list.
Edited markdown file.
I discovered this by following the docs and getting an error that the `dockerfile` param was not supported. Through trial and error I discovered that pluralizing made it work. To test, push a repo through CircleCI with this example config, and configure it with two different Dockerfiles you'd like to run through hadolint.
> Fix CircleCI example

- .travis.yml
- appveyor.yml
- docker/Dockerfile
- package.yaml
Adds a flag to the hadolint package that toggles static compilation.
By default I set it to `false` and enable this flag in the `Dockerfile`, 
`appveyor.yml` and `travis.yml`.
The reason is that some systems don't easily support static linking,
so using the flag when you want it is nicer instead of having to patch
around this problem.
I tested locally that it "works" without setting anything and that it "breaks" (for me on NixOS) when enabling the `static` flag.
We could also set the flag to `true` by default, and I would manually patch the package for NixOS, but it feels like disabling the static compilation by default is a saner default.  WDYT?
> Add cabal flag for static compilation

- docs/INTEGRATION.md
This is somehow new but I've been relying on such solution for longer time and it proven to be quite robust used both in shell and `neovim` integration.
Created an alternative approach to use `hadolint` via shim that gets installed somewhere into `$PATH`
Wrote simple [bin/hadolint](https://github.com/kornicameister/dotfiles/commits/master/bin/hadolint) shim longer while ago and have decided to extract it [here](https://github.com/kornicameister/hadolint-shim) for others to pick up if needed. There are editor integrations for sure but sometimes there is need to just do `hadolint` in `$SHELL` and it is much simpler to just do `hadolint Dockerfile` instead of `docker run ...` on systems that do not provide static binaries.
Following installation instruction …
> Add hadolint-shim

- docs/INTEGRATION.md
Emacs support handolint with the flycheck extension.
https://www.flycheck.org/en/latest/languages.html#dockerfile
> Add Emacs on the list of supported editors

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixes: #459
Fixes false-positive for `pipVersionNotPinned` when using `--trusted-host`; new test added.
> Support --trusted-host for pip install

- README.md
README.md file now clarifies how to pass a specific configuration YAML file (using its relative or absolute file path) to a container
via bind mount (`-v` option for docker) to customize the linter behavior, which checks the Dockerfile that is piped into the container.
Related issues:
* https://github.com/hadolint/hadolint/issues/308
* https://github.com/hadolint/hadolint/issues/346
> added description how to pass config into container

- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- test/Spec.hs
Add four rules for `yum` commands warning on bad practices:
* `yum update`
* `yum install` without non-interactive flag `-y`
* `yum install -y <pkg>` without version pinning
* `yum install ...` without also cleaning up with `yum clean all`
These four rules are accompanied by test for each rule.
Also included is a new helper function `Shell.anyCommands`.
Add four rules for linting `yum` commands in `RUN` layers. These four rules check for common mistakes and bad-practices with `yum` in Dockerfiles.
This PR is related to #470, but does not suffice to close it since `zypper` and `dnf` checks are still missing.
I expanded the `Rules.hs` file. I also added a new helper function in the `Shell.hs` file: `Shell.anyCommands` that works like `Shell.allCommands`, except it matches on any instead of …
> Rules: Add rules for `yum` commands, #470

- src/Hadolint/Shell.hs
- test/Spec.hs
This PR resolves issue #452. Problem was in wrong arguments ordering which was created by ShellCheck. For example, pip command mentioned in issue was cut down to:
```
[
CmdPart {arg = "install", partId = 6},
CmdPart {arg = "--index-url", partId = 8},
CmdPart {arg = "https://user:pass@eg.com/foo", partId = 12},
CmdPart {arg = "--extra-index-url", partId = 14},
CmdPart {arg = "https://user:pass@ex-eg.io/foo", partId = 18},
CmdPart {arg = "foobar==1.0.0", partId = 20}
]
```
Extra-index-url id is 14 and it tries to remove item with id 16, but that id doesn't exsist. 
Search for the smallest argument id which is greater than the flag id. 
Tests mentioned in issue was added in Spec file.
> Python pip basic auth | fixes [#452]

- src/Hadolint/Rules.hs
I add proxy flag in pip command array. 
```
--proxy <proxy>             Specify a proxy in the form [user:passwd@]proxy.server:port
```
> add proxy attribute | pip

- src/Hadolint/Rules.hs
Add simple test against a target path parsed as empty.
A trailing whitespace could cause the target path to be falsely parsed
empty and that would cause a crash with `Data.Text.last`.
fixes #448 
Add guard against crashing when the last argument of a `COPY` instruction ends with a whitespace.
The parser would assume the target path of the `COPY` instruction comes after the last whitespace, which would cause the target path to be empty in this case. That would crash the following operations on that target path.
Instead, now the rule evaluates to true.
See bugreport #448.
This fix is pretty crude and only prevents crashing. I am not sure if the behaviour now is satisfactory, since a trailing whitespace would trigger `DL3021`, causing a confusing message. This could be resolved by linting …
> bugfix: Fix crash on trailing whitespace #448

- package.yaml
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Lint.hs
- src/Hadolint/Rules.hs
A use case surfaced by #475 is that some people lint lots of files, and try to make things faster by running them in parallel using bash.
Running things in parallel in Haskell is trivial, so I went ahead and added this feature. After some superficial testing, found out that the best performance is reached at maximum 4 CPUs at a time. That's why I capped the `-N` to 4.
Whoever wants to experiment with more CPUs may invoke `hadolint` like this:
```
hadolint +RTS -N[num] -RTS Dockerfile1 Dockerfile2 Dockerfile3...
```
> Run the linter in parallel when multiple files supplied

- test/Spec.hs
Add tests making sure `yum` lint rules are not overzealous.
- Test against correct use of `yum` in each case
- Test against no use of `yum` at all in each case
Both times the rule should not trigger.
Run `stack test`. All tests should pass.
> Yum lint - Add negative tests

- package.yaml
- src/Hadolint/Formatter/Checkstyle.hs
- src/Hadolint/Formatter/Codacy.hs
- src/Hadolint/Formatter/Codeclimate.hs
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Formatter/Json.hs
- src/Hadolint/Formatter/TTY.hs
- stack.yaml
- Megaparsec has changed the `Stream` Typeclass.
- Reflect the upstream changes during usage of Megaparsec.
Fix build errors with Megaparsec >= 9.0.0
Fixes: #488 
Note: This breaks compatibility with Megaparsec < 9.0.0
Reflect the upstream changes in the `Stream` typeclass in the formatter code.
Here is the upstream commit that changed the interface: https://github.com/mrkkrp/megaparsec/commit/f8ef95c025f00dc3ea6bb2c78c71e89dc749f413
The following should work:
```
$ stack --resolver nightly-2020-11-11 build hadolint
$ stack --resolver nightly-2020-11-11 test
```
> formatter: support for megaparsec >=9.0.0 #488

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixes #485
- Exclude local archives from emitting DL3013.
- Test that local archives no longer emit DL3013
Emitting DL3013 for local packages is pointless, since the developer of the dockerfile controls what that local package is anyways and therefore also controls the version of the software within.
This Dockerfile no longer triggers DL3013:
```Dockerfile
RUN pip install mypkg.whl
RUN pip install mypkg.tar.gz
```
This Dockerfile still triggers DL3013:
```Dockerfile
RUN pip install numpy
```
PR also comes with unit tests.
> feature: `pip install` from local archive no longer emits DL3013 #485

- src/Hadolint/Rules.hs
- test/Spec.hs
Fixes #261 
- Strip quotes from argument of `WORKDIR`
- Test correct behaviour with single and double quotes
The following Dockerfile no longer triggers DL3000:
```Dockerfile
FROM debian:buster
ENV myworkdir "/var/lib"
WORKDIR /tmp
WORKDIR "/usr/src"
WORKDIR '/usr/local'
WORKDIR "${myworkdir}"
```
The following Dockerfile does still trigger DL3000 on all occasions:
```Dockerfile
FROM debian:buster
WORKDIR var/lib
WORKDIR "var/lib"
WORKDIR 'var/lib'
```
This is also reflected in unit tests.
> bugfix: false positive whith quoted `WORKDIR` #261

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
Resolves #467
Updated the rule for pip install when dealing with requirements files.
Moved the `requirementsInstall` function out of the `isPipInstall` function into the higher level `forgotToPinVersion`
Use the Dockerfile provided in the related issue.
There appears to be existing tests for this case that were passing when they should not have. Any suggestions for correcting this?
> Fixed requirements usage in pip install

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
Includes tests and reference to non-existing wiki page.
Resolves #455
Added a new rule for `pip --no-cache-dir` usage
Added the rule to `Rules.hs` and its exported `rules` list. This also factored out some code from the `pipVersionPinned` rule so that both rules can share the `isPipInstall` logic.
The provided tests and the Dockerfiles referenced in #455 and  #467
If this change is accepted I can create the related wiki entry, just let me know if that is needed.
> dl3038 pip --no-cache-dir rule

- .github/ISSUE_TEMPLATE.md
- .github/workflows/ghcr.io.yml
- README.md
- docker/README.md
- docs/INTEGRATION.md
closes #503 
I've created another workflow to build and deploy the container image to the GitHub Container Registry using the same scripts used by the DockerHub builder. This way, in case you need to modify the script, you don't have to worry about syncing the two builders.
I've created a secret under the repository named: `GHCR_IO_REGISTRY_TOKEN` with a personal access token with `write:packages` permissions. **Create it before triggering a new release.**
Also, you will need to **enable the improved container support** under your `hadolint` organization settings:
After the first release, you have to **mark the package as publicly accessible.**
I run the GitHub action in our SIGHUP's fork: https://github.com/sighupio/hadolint/runs/1474557615?check_suite_focus=true
> Add workflow to deploy the container images to ghcr.io

- src/Hadolint/Formatter/TTY.hs
- Add rule severity to tty output
- Fixes #495
Make tty output show severity of rules. Pretty small one-line change.
Take this Dockerfile:
```Dockerfile
FROM debian
RUN export node_version="0.10" \
&& apt-get update && apt-get -y install nodejs="$node_verion"
COPY package.json usr/src/app
RUN cd /usr/src/app \
&& npm install node-static
EXPOSE 80000
CMD ["npm", "start"]
```
It will produce this output:
```Shell
$ hadolint Dockerfile
Dockerfile:1 warning: DL3006 Always tag the version of an image explicitly
Dockerfile:2 warning: SC2154 node_verion is referenced but not assigned (did you mean 'node_version'?).
Dockerfile:2 info: DL3009 Delete the apt-get lists after installing something
Dockerfile:2 info: DL3015 Avoid additional packages by specifying `--no-install-recommends`
Dockerfile:5 …
```
> format: add rule severity to tty output #495

- src/Hadolint/Rules.hs
- test/Spec.hs
- Check for `apt-get dist-upgrade` in addition to the existing
check for `apt-get upgrade`
Performing `apt-get dist-upgrade` is to be considered bad practice for
the same reasons that `apt-get upgrade` would be considered bad
practice. Perhaps it should be considered worse in cases where an
appropriate base image is available.
Fixes #514
Add "dist-upgrade" to the list of command line arguments for apt-get to be checked for.
This should trigger `DL3005`:
```Dockerfile
RUN apt-get dist-upgrade
```
Unit tests are included.
> DL3005: Fix missing dist-upgrade #514

- app/Main.hs
- docs/INTEGRATION.md
- hadolint.cabal
- package.yaml
- src/Hadolint/Formatter/Codeclimate.hs
- src/Hadolint/Lint.hs
Close #521
First, I suffered a lot cause I am a newbie in haskell... :cry: 
Then, I implemented a formatter named   'gitlab_codeclimate' compatible with gitlab. This report will be json list of json object. Each object will contain a 'fingerprint' attribute containing sha1 of string representation of the object
- added cryptonic dependency
- added the option `gitlab_codeclimate`
- putting in each object a `fingerprint` attribute containing a `sha1` of the json representation of the object (without `fingerprint`attribute)
Launch binary with `gitlab_codeclimate`. The result will be
```
[{"location":{"path":"path/Dockerfile","lines":{"begin":49,"end":49}},"fingerprint":"d4b3531cf24f32c5d2a58671461ddd9ba9410c02","severity":"major","check_name":"SC1007","categories":["Bug …
```
> Implement codeclimate report compatible with gitlab

- .pre-commit-hooks.yaml
- README.md
- docs/INTEGRATION.md
Add a yaml configuration file to allow running hadolint as a git pre-commit hook with [pre-commit](https://pre-commit.com/).  Once set, the yaml hook configuration file doesn't need to change.  The hook allows either using a local hadolint binary or using the official hadolint Docker image.
Install pre-commit from the docs at https://pre-commit.com/ and install the hooks with `pre-commit install` in the git repository.  Add a `.pre-commit-config.yaml` file following the docs in this pull request, and then attempt to commit some staged changes to any Dockerfile into git.  `pre-commit` only runs on changed files by default so it won't run on any Dockerfiles that are not included in the current commit.
> add pre-commit hook configuration

- .pre-commit-hooks.yaml
This change updates the pre-commit hook for a local hadolint install to detect via filetype instead of filename.
The hadolint docker pre-commit hook already has this configuration but I missed setting it for the system hook in the initial PR.
This will allow pre-commit to detect Dockerfiles that don't have the exact filename of `Dockerfile` as there may be multiple Dockerfiles with different names in the same directory.
> Improve pre-commit file-type detection for dockerfiles

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
- Add rule to check agains illegal instructions within `ONBUILD`
instructions
- Modify rule parsing to do a pass with and a pass without automatically
expanded `ONBUILD` instructions
- Merge results of the two passes such that all rules appear once only
- Add tests for new rule
I'd like to point out two things for discussion regarding this change:
- In addition to the three cases checked here, IMO not all other combination that are legal by this rule make a lot of sense.
For example `ONBUILD EXPOSE` or `ONBUILD LABEL` do not appear very useful to me - maybe we should warn on them?
The requested three cases are to be avoided as per official docker documentation, so I think there is no need to discuss the necessity of linting for them.
- Checking the `ONBUILD` instructions themselves …
> rules: Check against illegal instructions within `ONBUILD` #512

- src/Hadolint/Rules.hs
- test/Spec.hs
- Make matching pip commands more accurate
Pip has a lot of different ways of calling (`pip`, `pip3`, `python -m pip`,
...). Some rules are pip specific, while others apply to wrappers around
pip as well. These wrappers include `pipenv` and `pipx`. The addition of
a isPipWrapper command lets a rule distinguish between pip commands and
wrappers.
fixes #532
fixes #511
I added an extensible way to distinguish between genuine `pip` commands and `pip` wrappers like `pipx`, when writing rules.
Simply excluding `pip` wrappers from matching should be up to the author of the individual rules, because a rule may apply to all `pip` commands including wrapper, or just the wrappers or just the genuine `pip` commands.
Use the `isPipWrapper` function to identify `pip` wrappers when linting through `pip` …
> bugfix: more accurate matching on `pip`

- app/Main.hs
- hadolint.cabal
- src/Hadolint.hs
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Lint.hs
Each formatter shall exit non 0 code when any error occurs unless '--no-fail' option specified. If so, a 0 status code is returned even if any rule is violated
Closes #391
Make program return non zero code if failure occurs, whenever the formatter. If `--no-fail` is specified , the programm returns `0` status code, whatever rules are violated or not.
- remove treatment of exit in lint and put it in main
- added option
- print result and analyse the exit method that shall be called
- launch binary with invalid `Dockerfile` with `-f gitlab_codeclimate` and expects `1`status code
- launch binary with invalid `Dockerfile` with `-f gitlab_codeclimate` and `--no-fail` and expects `0`status code
- launch binary with valid `Dockerfile` with `-f gitlab_codeclimate` and expects `0`status code
- …
> Add '--no-fail' option

- .github/workflows/release.yml
I broke it by forgetting to pass the static flag and the fPIC option to
GHC when moving the build script to github actions.
closes #534
> Restore static compilation

- app/Main.hs
- hadolint.cabal
- package.yaml
- src/Hadolint/Formatter/TTY.hs
- src/Hadolint/Lint.hs
- stack.yaml
- test/Spec.hs
- add `--color` flag to switch on colorization
- default off
- colorize TTY output:
error - bold red
warning - bold yellow
info - green
style - cyan/blue
As elaborated in issue #267, this enhances the experience with Hadolint
on the console.
Since currently there are no rules with the `style` severity, I can not showcase its color.
> feature: colorize TTY output  #267

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
- Add Rule to check agains `ENV` statements where one variable
references another variable defined within the same `ENV` statement.
- fixes #509
- Add tests for that rule
Docker will not expand environment variables within the same `ENV`
statement where they are defined.
The following Dockerfile will produce error DL3044:
```
ENV BLA="blubb" \
BLUBB="${BLA}/blubb"
```
That is because Docker will expand the environment variable `BLUBB` to `"/blubb"`, not as expected to `"blubb/blubb"`. This behaviour could cause bugs and build errors in docker images and therefore Hadolint should notice these situations.
> rules: Add rule checking agains selfreferencing `ENV`s

- app/Main.hs
- hadolint.cabal
- package.yaml
- src/Hadolint/Config.hs
- src/Hadolint/Formatter/Checkstyle.hs
- src/Hadolint/Formatter/Codacy.hs
- src/Hadolint/Formatter/Codeclimate.hs
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Formatter/Json.hs
- src/Hadolint/Formatter/TTY.hs
- src/Hadolint/Lint.hs
- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- test/ConfigSpec.hs
- test/Spec.hs
- Make rule severity overridable with any other severity.
- Remove unnecessary imports
This feature is implemented with a custom rule severity type
`DLSeverity` which encapsulates the possible severities, including the
possibility that a rule is ignored by default.
The is my second attempt at the long requested feature of customizable rule severeties.
It is an alternative implementation of the customizable rule severities, without using a `Maybe Severity`. Instead this is implemented with a custom `DLSeverity` type. This also is not intermingled with another different feature, which should make reviewing much easier. That said, it is missing an example of an opt-in rule.
The `DLSeverity` type is constructed analogous to the `Severity` type from `Shellcheck`, which was used before. This …
> Feature: Configurable rule severity

- package.yaml
- stack.yaml
- test/Spec.hs
- Bump version of language-docker to 9.1.3
- Bump version of Hadolint to 1.22.2
- Add regression test for #510
fixes #510
Parsing an `ARG` with an equals sign, but without a value was fixed upstream. This version bump pulls the upstream fix into Hadolint.
The following Dockerfile should no longer confuse the parser and generate misleading errors:
```Dockerfile
ARG BLA=
RUN echo
```
> bump: language-docker v9.1.3, hadolint 1.22.2

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
- Keep track of what `ENV`s and what `ARG`s have been defined in
rule DL3044.
When a variable is already defined, it is ok to reference it, even when
redefining that variable in an `ENV` statement.
The behavior described in #551 is tested for in unit tests.
This fix works by maintaining a list of defined variable names and excluding those when searching for occurrences of variables within the right hand side of the definition of variables. This list is fed by variables defined both in `ENV` and in `ARG` statements.
@lorenzo I think I have all possible cases of partial and full matches covered with the unit test, but please take a second and see if you can find some that I haven't covered yet.
fixes #551
> regression: Fix regression   #551

- hadolint.cabal
- package.yaml
- src/Hadolint/Rules.hs
- test/Spec.hs
- Allow a variable to reference itself in its definition once per `ENV`
statement
- Add tests for new behavior
A variable may legitimately be redefined with itself e.g.
`PATH=/path:${PATH}`, thus this case should not trigger DL3044. However
doing so twice or more within the same `ENV` statement will not expand
the variable twice and therefore should be an error.
see https://github.com/hadolint/hadolint/pull/548#issuecomment-785800548
When searching for occurrences of the variable as reference (either $VAR or ${VAR}), the right hand side value of the variable itself is no longer searched. Only the right hand sides of other variables in the same `ENV` statement is searched. To implement this, an indexed list is used to uniquely identify the variable/value pairs. This can not be done by …
> rules: refine selfreferencing env rule

- README.md
- src/Hadolint/Rules.hs
- test/Spec.hs
- Add rule finding instance of `COPY` with a relative destination when
no `WORKDIR` has been set.
- Add tests for that rule
The rule permits not setting a `WORKDIR` in case the `WORKDIR` is
already set in a previous build stage (in the same Dockerfile)
form which it is inherited.
The rule always permits absolute destinations.
fixes  #390
This Rule tracks whether or not a `WORKDIR` has been set in a build stage. In case a `COPY` with a relative destination occurs, but the `WORKDIR` has not been set (yet) in that build stage or any previous build stage that stage inherits from, it raises a warning.
The most complicated part is tracking which stage has a `WORKDIR` set, since they can inherit a `WORKDIR` from a previous stage and can have multiple `WOKRDIR` instructions. Therefore, the rule …
> Add rule for `COPY` when no `WORKDIR` is set  #390

- src/Hadolint/Rules.hs
- test/Spec.hs
- do not trigger DL3045 when the destination of the `COPY`
statement is or begins with a variable.
- strip quotes from destination string
When the destination of a `COPY` statement is or begins with a
variable, it can be assumed, that the programer takes responsibility for
setting that variable.
fixes #560
Exclude the case where the destination is a variable from DL3045. When looking at the original feature request https://github.com/hadolint/hadolint/issues/390, the case where the destination of the `COPY` statement is a variable is not really a problem this rule should warn about, since it is unaffected by unwanted interaction of the `WORKDIR` and `COPY` statements.
One can argue, that `COPY`ing to a destination that is a variable that has not been set or has been set to a relative …
> DL3045: fix when destination is a variable

- README.md
- hadolint.cabal
- src/Hadolint/Rules.hs
- src/Hadolint/Shell.hs
- test/ShellSpec.hs
- test/Spec.hs
- Add rule to lint for missing flag `-l` during usage of `useradd` with
long UIDs.
- Number is DL3045 in anticipation of DL3044 being merged
- Add tests for that rule
- Add function to exctract arguments to a flag from shell command arguments
- Add unit test module for the `Hadolint.Shell` module
- Add test the functions `getFlagArg` and `hasFlag`
fixes #553
This rule triggers when the argument following the `-u` flag of `useradd` is longer than 5 characters and the `-l` flag is absent.
The threshold of 5 was determined experimentally by increasing the UID until the resulting image size changed, but also matches the default UID_MAX value of 65535 for most Linux systems.
Also notable is the addition of unit tests for the `Hadolint.Shell` module.
Either of these Dockerfiles should be ok: …
> rules: add rule linting `useradd`  #553

- README.md
- hadolint.cabal
- src/Hadolint/Process.hs
- src/Hadolint/Rule/DL3047.hs
- test/Spec.hs
Implements #546
Signed-off-by: Michał Sochoń <kaszpir@gmail.com>
- add  basic tests
- add new rule file 3047
- extend Spec.hs and Process.hs
- auto-updated hadolint.cabal
- created basic tests
- use basic file such as https://github.com/hadolint/hadolint/blob/4db396caa9d0497e310d5eda532e0ca1d7bb1e3a/src/Hadolint/Rule/DL3046.hs as a base
- iterate by hand and lot of trial and error.
```
stack test
```
See new section:
```
Wget no progress
warns when using wget without progress option
does not warn when running with progress option
```
> Add suggestion to run wget with --progress=dot:giga

- hadolint.cabal
- src/Hadolint/Process.hs
- src/Hadolint/Rule/DL3012.hs
- src/Hadolint/Rule/DL3057.hs
- test/Spec.hs
- Add rule DL3012 that makes sure no stage has two `HEALTHCHECK`
instructions
- Add rule DL3057 that makes sure every stage has one `HEALTHCHECK`
instruction.
This rule disabled by default and can be enabled by overriding its
severity.
fixes #360
Third time's the charm, right? As promised here https://github.com/hadolint/hadolint/pull/555#issuecomment-801004824, this is the PR with the two rules wrt. `HEALTHCHECK` instructions.
> healthcheck: Rules for checking HEALTHCHECK instructions

- src/Hadolint/Rule/DL3044.hs
- test/Spec.hs
When a variable is defined in terms of another variable and that other
variable is not referred to with curly-baces notation, the definition of
the first variable is split on the variable name. This results in a list
of remaining strings. The beginnings of the remaining strings is used to
determine, if the variable name that was found was just a substring of
another variable name, or is the actual variable. This is done by scanning
the beginnings of these strings for characters that terminate a variable name.
If one such character is found, the variable name looked for is actually found
and not just a substring of another variable name.
Since the `Text.splitOn` also returns the first part before the
variable, it is wrongfully determined, that the variable was found in
cases where its name …
> dl3044: fix bug with variable detection

- README.md
- app/Main.hs
- hadolint.cabal
- package.yaml
- src/Hadolint/Config.hs
- src/Hadolint/Process.hs
- src/Hadolint/Rule.hs
- src/Hadolint/Rule/DL3048.hs
- src/Hadolint/Rule/DL3049.hs
- src/Hadolint/Rule/DL3050.hs
- src/Hadolint/Rule/DL3051.hs
- src/Hadolint/Rule/DL3052.hs
- src/Hadolint/Rule/DL3053.hs
- src/Hadolint/Rule/DL3054.hs
- src/Hadolint/Rule/DL3055.hs
- src/Hadolint/Rule/DL3056.hs
- stack.yaml
- test/ConfigSpec.hs
- test/Spec.hs
- Add configuration options to describe a label schema to Hadolint.
- Add commandline option --require-label, which can also describe a
label schema to Hadolint
- Add a rule that alerts on any label that is not specified to be
present
- Add a rule generator, which generates rules that check the existence
of labels described in the label schema.
- Add a rule generator for generating rules that check that labels have
a valid URL as value
- Add a rule generator for generating rules that check that labels have
a valid time stamp according to RFC3339 as value
- Add a rule generator for generating rules that check that labels have
a valid SPDX license identifier as value
- Add a rule generator for generating rules that check that labels have
a valid git hash as value
fixes #480 
fixes #199 …
> label-schema: Add configurable rules checking a label schema

- src/Hadolint/Rule/DL3045.hs
- test/Spec.hs
- Fix workdir detection on `ONBUILD` context by allowing the current
stage to take the special value `None`, since an `ONBUILD` context has
no current build stage.
- Add test cast specifically testing this case
fixes: #573
With the larger restructuring, the way `ONBUILD` instructions are linted has changed. Now the rules are executed on a filtered version of the dockerfile, only containing the lines with `ONBUILD` instructions. This strips the `FROM` instructions out of the input to the rules, breaking rules that rely on finding at least one `FROM` instruction to initialize.
This fix concerns only rule DL3045 by modifying its state to allow for the possibility that the current context has no `FROM` instruction.
The following dockerfile should no longer trigger DL3045
```Dockerfile
FROM …
```
> DL3045: Fix workdir detection in `ONBUILD` context

- src/Hadolint/Rule/DL3016.hs
- src/Hadolint/Shell.hs
- test/DL3016.hs
- test/ShellSpec.hs
- Add unit test case for `Shell.dropFlagArg`
- Add unit test case for DL3016 with `--loglevel verbose`
- make DL3016 ignore the arguments to named flags and not mistage them
as packages
- move helper functions for DL3016 to top level and name their type
signatures
- fixup `Shell.getFlagArg` to use a `Set` instead of a raw list
- remove superfluous use of `Text.pack` from `test/Shellspec.hs`
fixes #515
As I don't have very much experience with `npm`, there may very well be other flags that should have their arguments ignored as well, but from a quick glance over the documentation, I could not make out any.
The following Dockerfile should no longer emit `DL3016`:
```Dockerfile
RUN npm --loglevel verbose install foo@1.0.0
```
> DL3016: fix mistakenly interpret argument to flag as package

- README.md
- hadolint.cabal
- src/Hadolint/Process.hs
- src/Hadolint/Rule/DL3060.hs
- test/DL3060.hs
- Add new rule DL3060 linting for `yarn cache clean` after `yarn
install` with severity `DLInfoC`
- Add tests
This rule reminds the odd programmer about cleaning `yarn`s caches after
installing, just like with the other package managers.
fixes: #395
This should trigger `DL3060`:
```Dockerfile
RUN yarn install foo
```
This should be fine:
```Dockerfile
RUN yarn install foo \
&& yarn cache clean
```
> DL3060: Lint for `yarn cache clean` #395

- README.md
- hadolint.cabal
- src/Hadolint/Process.hs
- src/Hadolint/Rule/DL3059.hs
- test/DL3059.hs
- test/ShellSpec.hs
- test/Spec.hs
- Add new rule linting for multiple consecutive run instructions that
could be consolidated.
- Add tests for that rule.
On of the first bullet points in the Docker best practices is that one
should merge multiple `RUN` instructions into one, where possible to
reduce the layer count:
https://docs.docker.com/develop/dev-best-practices/
This rule informs with a severity of `DLInfoC`, where this is possible.
The following should trigger rule DL3059:
```Dockerfile
RUN /foo.sh
RUN /bar.sh
```
None of these should trigger rule DL3059:
```Dockerfile
RUN /foo.sh
WORKDIR /
RUN /bar.sh
```
```Dockerfile
RUN /foo.sh \
&& /bar.sh
```
I have omitted `onBuildRuleCatches[Not]` unit tests, because they don't behave properly. In particular, this one:
```Haskell
onBuildRuleCatchesNot "DL3059" "RUN …
```
> DL3059: Multiple consecutive `RUN` instructions

- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Formatter/Json.hs
- test/Spec.hs
Fix `message` field in output by json formatter in case of errors
preventing rule application (e.g. parsing errors).
Previously, a pretty printing method from `Text.Megaparsec.Error` was
used, but this decorated the message with junk characters. The new
`errorMessage` function converts a `ParseErrorBundle` into a printable
`String` without additional junk, stripping newlines from the end as
well.
fixes: #593
Executing `hadolint -f json Dockerfile` for the following Dockerfile should yield `[{"line":1,"code":"DL1000","message":"missing whitespace","column":4,"file":"/home/moritz/tmp/Dockerfile","level":"error"}]`:
```Dockerfile
RUNNN
```
> json-formatter: fix error message

- src/Hadolint/Rule/DL3059.hs
- test/DL3059.hs
Refine behaviour of DL3059 when dealing with `RUN` flags. These flags
are Docker buildkit specific, but may significantly alter behaviour of
`RUN` commands.
- Do warn when two consecutive `RUN` instructions are found with the
same flags
- Do not warn when two consecutive `RUN` instructions have differen
flags
As explained in [this discussion](https://github.com/hadolint/hadolint/pull/591#issuecomment-814595691) consolidation of consecutive `RUN` instructions may be undesired, if there are different flags for each of the instructions. In addition to that, consolidation may not be possible, if both `RUN` instructions have flags, but the flags are different.
These Dockerfile should no longer trigger DL3059:
```Dockerfile
RUN --mount=type=secret,id=foo /foo.sh
RUN /bar.sh
```
```Dockerfile …
```
> DL3059: improve behaviour when considering flags

- README.md
- add description of the `email` property to the label schema
documentation
- add docker usage for windows users
- add documentation for rule severity overrides
fixes: #513
> readme: add email to label-schema, windows docker usage

- src/Hadolint/Rule/DL3042.hs
- test/DL3042.hs
Make DL3042 respect `PIP_NO_CACHE_DIR` variable, when it is set with an
`ENV` instruction.
fixes: #585
~This fix only applies when `PIP_NO_CACHE_DIR` is set via the `ENV` instruction. This is because Hadolint does not expose the whole Shellcheck AST internally, so when parsing something like `RUN export PIP_NO_CACHE_DIR=1`, the export command is exposed, but the environment variable is not - at least not easily.~
Fixed the recognition of `PIP_NO_CACHE_DIR` within the `RUN` instruction as well.
```Dockerfile
RUN PIP_NO_CACHE_DIR=1 pip install wheel
RUN export PIP_NO_CACHE_DIR=1 && pip install numpy
ENV PIP_NO_CACHE_DIR=1
RUN pip install six
```
should no longer trigger DL3042.
> DL3042: respect `PIP_NO_CACHE_DIR` variable

- app/Main.hs
- contrib/hadolint.json
- hadolint.cabal
- package.yaml
- src/Hadolint/Config.hs
- src/Hadolint/Lint.hs
- test/ConfigSpec.hs
- add new option `--threshold`/`-t` for specifying a failure threshold
The specified failure threshold (info by default) will cause hadolint to
not return with a failure code when only rules with a lesser severity
are violated.
Accepted values are `error`, `warning`, `info`, `style`, `ignore` and
`none`, where `info` is the default and `ignore` and `none` both cause
Hadolint to exit with an error code if any rule is violated. A threshold
of level `error` has the same effect as passing `--no-fail`.
fixes: #607
> options: introduce failure severity threshold

- src/Hadolint/Config.hs
`.yaml` is [functionally identical](https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml) to `.yml` and hence, users should be able to specify the config file in either format for `hadolint`.
This closes #614 
This PR adds support for an additional config file `.hadolint.yml` for `hadolint` to use. Existing functionality was kept intact and `hadolint` should prefer the extension `.yaml` still over `.yml`. 
Changes `findConfig` from taking `FilePath` to a list of `FilePath`. Adds a constant called `acceptedConfigs`
> refactor(config.hs): adds additional accepted config file

- app/Main.hs
- src/Hadolint/Config.hs
Users want to know what is the configuration file used so that troubleshooting in the event of errors can be made easier
Closes #610 
This PR adds a flag that, when set, displays the configuration file used.
1. always printing the configuration file at invocation of `hadolint`. this was decided against because this should be an opt in feature as there might be a significant majority of users using `hadolint` as is. 
1. invoke `hadolint` with the `-h` option. verify that the show config option is there.
2. invoke `hadolint` with `-V` or `--verbose` but without a configuration file specified. `hadolint` should work but print a message notifying the user that there is no configuration file found.
3. invoke `hadolint` with `-V` or `--verbose` with a valid configuration file specified. …
> feat(main): log configuration file used

- src/Hadolint/Rule/DL3060.hs
- test/DL3060.hs
- test/Spec.hs
- Enable tests for DL3060
- Make failure logic stage aware, meaning that a `yarn install` without
a `yarn cache clean` will not trigger DL3060 anymore in build stages,
but will still trigger in the final image.
fixes: #619
```Dockerfile
FROM node:lts-alpine
RUN yarn install
FROM node:lts-alpint
RUN foo
```
should no longer trigger DL3060, while
```Dockerfile
FROM node:lts-alpine as stage1
RUN yarn install
FROM stage1
RUN foo
```
still should trigger DL3060.
> DL3060: stage aware logic

- .github/workflows/thirdparty.yaml
- src/Hadolint/Config.hs
Closes #622 .
I added a new GitHub action that creates/updates a `ThirdPartyNotices.txt` file, which contains the license types for all its (transitive) dependencies.
The action is built around [licensor v0.4](https://hackage.haskell.org/package/licensor).
- A successful action run looks like [this](https://github.com/janjagusch/hadolint/actions/runs/807661288).
- You can see that the action does not commit anything if the `ThirdPartyNotices.txt` hasn't changed [here](https://github.com/janjagusch/hadolint/runs/2494433558?check_suite_focus=true).
> Add GitHub action to update/create ThirdPartyNotices.txt

- src/Hadolint/Config.hs
- src/Hadolint/Lint.hs
- src/Hadolint/Rule.hs
- test/ConfigSpec.hs
Parsing the contents of the `failure-threshold` property was done
improperly and resulted in all results being discarded in case the
property was absent. The observed behaviour was seemingly the same as if
the config file had not been found, but in fact it was a problem of the
parser.
- Make all severity overrides more solid as types by implementing the
to-be-overridden rules as rule codes instead of `Text.Text`s
- Make `DLSeverity` an instance of `Yaml.FromYAML`, `Semigroup` and
`Monoid` to properly handle parsing from yaml files and combining
multiple severities.
With `DLSeverity` being a more sophisticated type and implementing its
own yaml parser, parsing the config and combining it with the
configuration obtained from commandline options has much more consistent
behaviours with …
> config: fix parsing problems

- README.md
- hadolint.cabal
- package.yaml
- src/Hadolint/Config.hs
- stack.yaml
- test/Spec.hs
- Bump version of language-docker to 10.0.0
- Fix documentation for config file paths
- Fix search behaviour for config files to be backwards compatible
and match documentation.
> language-docker: version bump

- README.md
I've updated README.md to use correct config path used in Docker containers, and removed relative path example, as Docker requires an absolute one. 
Edited the README.md.
Verify wrong path, as rules from the `/some/project/hadolint.yaml` file will be ignored:
```bash
$ docker run --rm -i -v /some/project/hadolint.yaml:/root/.config/hadolint.yaml hadolint/hadolint < Dockerfile
-:7 DL4006 warning: Set the SHELL option -o pipefail before RUN with a pipe in it. If you are using /bin/sh in an alpine image or if your shell is symlinked to busybox then consider explicitly setting your SHELL to /bin/ash, or disable this check
-:13 DL3041 warning: Specify version with `dnf install -y <package>-<version>`.
```
Verify relative paths are not possible:
```bash
$ docker run --rm -i -v …
```
> Update config path in a Docker container

- .pre-commit-hooks.yaml
fixes https://github.com/hadolint/hadolint/issues/628
The version of docker image is fixed in .pre-commit-hooks.yaml
Just added tag
```
---
repos:
- repo: https://github.com/mathbunnyru/hadolint.git
rev: asalikhov/pre_commit_docker_version
hooks:
- id: hadolint-docker
```
If I prune docker images, on the first run it's easy to see, that exact version is pulled from docker:
`docker image rm hadolint/hadolint:v2.3.0`
`pre-commit run --all-files --verbose`
```
Unable to find image 'hadolint/hadolint:v2.3.0' locally
v2.3.0: Pulling from hadolint/hadolint
4fc54f9b225a: Pull complete
Digest: sha256:5bd624ce29f153036a3b03083af66f9ac040d2cb0673b2b4785394425e66f10b
Status: Image is up to date for hadolint/hadolint:v2.3.0
Unable to find image 'hadolint/hadolint:v2.3.0' locally
v2.3.0: Pulling from …
```
> Fix hadolint docker image in .pre-commit-hooks.yaml

- app/Main.hs
This is a follow-up on hadolint#607. The given threshold is inclusive. I.e. setting threshold to `info` will cause exit code 1 when rules with a severity above **or equal** to `info`  are violated. The docs should reflect that.
Update; My test that lead to this conclusion seems broken. See discussion in https://github.com/hadolint/hadolint/pull/613#pullrequestreview-656369769.
> Fix docs on failure-threshold option

- src/Hadolint/Rule/DL3045.hs
- test/DL3045.hs
- fix index overrun in DL3045 with single character paths when checking
for windows type paths.
fixes: #638
> bugfix: avoid index overrun in DL3045

- app/Main.hs
- hadolint.cabal
- src/Hadolint.hs
- src/Hadolint/Formatter/SonarQube.hs
- Add formatter for outputting json objects compatible with SonarQube's
generic [import format](https://docs.sonarqube.org/latest/analysis/generic-issue/)
All parse errors appear as code "DL1000" with severity BLOCKER and type
BUG. All rule violations with severity DLErrorC have type BUG and
severity CRITICAL, all other rule violations have type CODE_SMELL and
the appropriate severity MAJOR, MINOR, INFO respectively.
fixes: #626
> formatters: add SonarQube formatter

- .pre-commit-hooks.yaml
Related: https://github.com/hadolint/hadolint/issues/628
Please, next time update this before creating a release.
This way the release (basically, zip file), will get the same docker version as the release and it will be consistent.
> Update docker version in pre-commit-hooks

- src/Hadolint/Rule/DL4006.hs
- src/Hadolint/Shell.hs
- test/DL4006.hs
- test/Shellcheck.hs
- Ignore execution of shellcheck rules and DL4006 for non-posix shells
other than pwsh as well, where said rules are not applicable.
fixes: #644 #431
Expand the list of shells known to break with shellcheck and avoid execution of shellcheck when they are set as `SHELL`.
There are tests for the relevant rules (Shellcheck and DL4006), but also this Dockerfile for example should no longer be complained about:
```Dockerfile
FROM mcr.microsoft.com/powershell:ubuntu-16.04
SHELL [ "cmd", "-c" ]
RUN Get-Variable PSVersionTable | Select-Object -ExpandProperty Value
```
> shellcheck: ignore non-posix shells

- app/Main.hs
The help message suggests that the failure threshold makes Hadolint exit
with failure when a rule above **or equal to** the threshold is
violated. This was introduced to the help message with
https://github.com/hadolint/hadolint/pull/639/commits/3121fe9d79e609979f7c5bfe5704ba22c5af7bc6
But never updated the behaviour to match the help message.
fixes: #651
> threshold: tune behaviour to match help message

- app/Main.hs
- src/Hadolint.hs
- src/Hadolint/Formatter/Checkstyle.hs
Enhancement https://github.com/hadolint/hadolint/issues/529
I added a new command option `'file-path-in-report'`.
If the `'checkstyle'` format is selected and this new option is selected it will allow the user to define the file path referenced in the generated report and will override the input source file path which is taken by default.
This solves the problem that occurs when you run Hadolint with Docker and `checkstyle` format and the input source file path may not be the correct path i.e., it may default to '-' or '/dev/stdin' or the local container file path.
The correct file path is needed if you need your pipeline to integrate with something like [Jenkins Warnings Ng Plugin](https://www.jenkins.io/doc/pipeline/steps/warnings-ng/) which cross references the line numbers in the …
> Add file-path-in-report option for checkstyle format

- src/Hadolint/Formatter/SonarQube.hs
The Sonarqube output format forbids having equal start- and endcolumns
in the report for an issue. This commit changes the start column to 0
and leaves the end-column at 1, thus always marking an issue at the
first character of the corresponding line.
fixes: #658
> sonarqube-formatter: fix start column  #658

- src/Hadolint/Rule/DL3047.hs
As @lorenzo mentioned in #546, it's okay to lower it down.
Lower severity level of DL3047 to info, instead of warn
Simply change its severity from `DLWarningC` to `DLInfoC`
Simply write a Dockerfile and add a `RUN` instruction with `wget` command, use Hadolint to lint it. 
The result should be like:
```
Dockerfile:10 DL3047 info: Avoid use of wget without progress bar. Use `wget --progress=dot:giga <url>`.Or consider using `-q` or `-nv` (shorthands for `--quiet` or `--no-verbose`).
```
cc #546 #566
> Lower severity level of DL3047 to info

- app/Main.hs
The sonarqube formatted was added in the `2.5.0` release. This commit adds the option to the cli (which already accepts it).
> app/main: add sonarqube to cli output

- src/Hadolint/Rule/DL3018.hs
- test/DL3018.hs
DL3018 ensures version pinning. When installing from an .apk file, this
is pointless and should not trigger the rule, since it is equivalent to
version pinning.
fixes: #662
This should no longer trigger DL3018:
```Dockerfile
RUN apk add mypackagefile-1.1.1.apk
```
Test case included.
> DL3018: Don't trigger when installing from .apk file  #662

- src/Hadolint/Rule/DL3009.hs
- src/Hadolint/Rule/DL3019.hs
- test/DL3009.hs
- test/DL3019.hs
In case the cache directories DL3009 and DL3019 respectively are
provided via BuildKit cache mount, the two rules need not warn a user to
remove the directories.
fixes: #671
The following Dockerfiles should no longer emit warnings DL3009 or DL3019 respectively:
```Dockerfile
FROM alpine:3.14.0
RUN --mount=type=cache,target=/var/cache/apk apk add -U curl=7.77.0-r1
```
```Dockerfile
FROM debian:10
RUN --mount=type=cache,target=/var/lib/apt/lists/ apt-get update && apt-get install foo
```
> Feature: Silence DL3009,DL3019 for cache mounts

- src/Hadolint/Rule.hs
- src/Hadolint/Rule/DL3010.hs
- src/Hadolint/Rule/DL3020.hs
- test/DL3010.hs
- test/DL3020.hs
DL3020:
- Don't warn that the user should use `ADD` instead of `COPY`, as this
has the same result since zip files are not extracted.
DL3010:
- Don't suggest using `ADD` when copying from a previous build stage,
as `ADD` does not support copying from previous build stages.
General:
- Unify the list of archive extensions to reduce data duplication.
fixes: #679
fixes: #676
> DL3010, DL3020: fix edge-cases for archives

- hadolint.cabal
- package.yaml
- stack.yaml
- Bump version of language-docker to 10.1.1
- Bump version to 2.7.1
Pull in fixes from upstream language-docker, so the line continuation
bug in heredoc parsing gets fixed.
fixes: https://github.com/hadolint/hadolint/issues/699
> heredocs: fix line continuation bug

- src/Hadolint/Rule/DL3020.hs
Added ignore case to DL3020
fixes #693
Added two more string to test against
```
ADD "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" /tmp
```
should not trigger DL3020 anymore
> Feature: Silence DL3020 even for doube quoted URLs #693

- ThirdPartyNotices.txt
- hadolint.cabal
- package.yaml
- src/Hadolint/Rule.hs
- src/Hadolint/Rule/DL3000.hs
- src/Hadolint/Rule/DL3020.hs
- stack.yaml
- test/DL3020.hs
Generalize the bugfix in DL3020 from a few days ago. This really was about dropping quotes around a string and not about matching quotes at the beginning of a string.
Also bumping versions to incorporate the bugfix regarding heredoc termination in language-docker.
This should parse fine now:
```Dockerfile
RUN <<EOF
echo $EOF
EOF
```
Tests for the quote dropping mechanic in DL3020 are included.
> Drop quotes

- src/Hadolint/Rule/DL3033.hs
- src/Hadolint/Rule/DL3041.hs
- test/DL3033.hs
- test/DL3041.hs
Fix false positive in DL3033 and DL3041 when dealing with modules. See
https://docs.fedoraproject.org/en-US/modularity/installing-modules/ for
reference wrt. modules.
fixes: #702
The following Dockerfile should no longer trigger DL3041:
```Dockerfile
FROM registry.access.redhat.com/ubi8/ubi:latest
RUN dnf module install nginx:1.18 -y && \
dnf clean all --assumeyes
```
> bugfix: handle yum/dnf modularity   #702

- app/Main.hs
- hadolint.cabal
- package.yaml
- src/Hadolint.hs
- src/Hadolint/Formatter/Sarif.hs
- src/Hadolint/Meta.hs
Add formatter for SARIF output format. SARIF is the static analysis
results interchange format, a Microsoft/OASIS standard format for static
analysis tools.
See https://github.com/microsoft/sarif-tutorials
and https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html
Break long lines in `app/Main.hs`.
`hadolint -f sarif Dockerfile` should generate a valid SARIF report for that dockerfile. Tools like [jsonschemavalidator](https://www.jsonschemavalidator.net/) can be used to validate the output against the schema spec.
Example dockerfile with output:
```Dockerfile
FROM debian:latest
WORKDIR ./foobar
RUN echo $foo
```
> fomatters: Add SARIF formatter

- src/Hadolint/Rule/DL3059.hs
- test/DL3059.hs
Fixes #712
- added tests
- added code to DL3059 so that comments in the Dockerfile won't change the state (the state keeps track of the last line and if it was a `RUN` command.
Just added a case to the pattern matching, which makes the `otherwise` clause not get the comment-instructions.
Run the tests and/or run hadolint on the Dockerfile from the issue.
> DL3059: RUNs and comments mixed

- src/Hadolint/Rule/DL3034.hs
- test/DL3034.hs
Whitelist `--non-interactive, -n` zypper install options.
from the zypper command help
```
--non-interactive, -n	Do not ask anything, use default answers
-y, --no-confirm            Don't require user interaction. Alias for the --non-interactive global
option.
```
> DL3034: support --non-interactive and -n

- hadolint.cabal
- package.yaml
- src/Hadolint/Rule/DL3010.hs
- test/DL3010.hs
- Add advanced logic to DL3010 to detect archive extraction.
- Add more specific tests for DL3010
Sometimes it is desired to copy an archive into a Docker image. In these
cases, DL3010 should not trigger. This can be detected by searching for
commands extracting an archive that was added by a `COPY` instruction
earlier.
The new behaviour triggers only if an archive is `COPY`ed into the image
_and_ extracted (e.g. by `RUN tar -xf archive-foo.tar.gz`).
fixes: #709
> DL3010: Allow intentionally unextracted archives

- src/Hadolint/Meta.hs
Construct the version string correctly when not compiling in a git
directory.
This bug was caused by a typo and a misunderstanding of the code when
the version string logic was moved from app/Main.hs to
src/Hadolint/Meta.hs in commit 3b1de5a
fixes: #730
To verify that this actually fixes the issue, check out this commit, remove or rename the `.git` directory and compile Hadolint from source. The result should show the version string from the `.cabal` file and the `-no-git` ending.
```
$ hadolint -v
Haskell Dockerfile Linter 2.8.0-no-git
```
When compiling from source with the `.git` directory, the result should show the corresponding git tag and the short git hash.
> bugfix: display version string correctly

- src/Hadolint/Config/Configuration.hs
- test/Hadolint/Config/ConfigfileSpec.hs
Fix regression introduced by bf7e48e where the key for configuring the
set of trusted registries had changed.
fixes:  #733
Config files that worked previous to v2.8.0 should work work again. Specifically, the key `trustedRegistries` should work as described in the documentation.
> config: fix config file key `trustedRegistries`

- src/Hadolint/Rule/DL3007.hs
- test/Hadolint/Rule/DL3007Spec.hs
Hello there! 👋 
Thank you for creating and maintaining hadolint! I stumbled upon it about a month ago and it really helped me preventing some footguns. I love the fact this linter can save some of my time 👍 
I found an edge case. Docker allows both tags and SHA to be defined in the same base image definition. When this case happens, Docker ignores the tag and just pulls the image associated to its SHA.
Although, Docker ignores the tag, I find the case for having both compelling for humans: it's easier to represent what the image behind a SHA is, if the tag is next to it. 
I used this pattern and usually, hadolint is happy with it. Today, one of the tags was explicitly set to `latest` and `hadolint` bailed out. Here's a patch that changes the behavior to make it consistent no matter what …
> DL3007: Do not error out when latest tag is used alongside a sha256

- README.md
- hadolint.cabal
- src/Hadolint/Config/Commandline.hs
- src/Hadolint/Config/Configuration.hs
- src/Hadolint/Config/Environment.hs
- src/Hadolint/Pragma.hs
- src/Hadolint/Process.hs
- src/Hadolint/Rule/DL1001.hs
- test/Hadolint/Config/CommandlineSpec.hs
- test/Hadolint/Config/ConfigfileSpec.hs
- test/Hadolint/Config/ConfigurationSpec.hs
- test/Hadolint/Config/EnvironmentSpec.hs
- test/Hadolint/Rule/DL1001Spec.hs
- Add new configuration option allowing to disable inline ignore pragmas
- Add new rule DL1001 to allow warning on use of an inline ignore pragma
Inline ignore pragmas `# hadolint ignore=DLxxxx` can cause trouble in
organizations when it is not desirable that individual developers
circumvent centralized CI checks. This configuration options allows
(e.g. in such a CI pipeline) to just ignore the pragma and apply all
rules as usual. The option can be enabled via command line
`--disable-ignore-pragma`, environment variable
`HADOLINT_DISABLE_IGNORE_PRAGMA=1`, or config file
```yaml
disable-ignore-pragma=true
```
Just to prevent any confusion about the ignored pragma, the rule DL1001
can be used to fail the linting process regardless of how the dockerfile
fares, if desired. By default DL1001 …
> options: disable ignore pragma

- src/Hadolint/Rule/DL3021.hs
- test/Hadolint/Rule/DL3021Spec.hs
DL3021 makes sure the target path is a directory by making sure it ends
with a `/` if there are more than two arguments to a `COPY` instruction.
This should work regardless of whether or not that target path is
quoted.
fixes: #749
This should no longer erroneously trigger DL3021:
```Dockerfile
COPY fileA fileB fileC "/var/lib/destination/"
```
> DL3021: Fix behavior with quotes in target path

- test/Hadolint/Formatter/SarifSpec.hs
- test/Helpers.hs
- Test the result of the SARIF formatter by re-decoding the result and
comparing it against a known good JSON value. This removes the tests
dependence on the order the elemets of JSON object are printed in, which
is not necessarily deterministic.
- Extend the test suite for the SARIF formatter to test non-empty
linting results.
possibly fixes:  #753
> Tests: Fix test suite for SARIF formatter

- src/Hadolint/Config/Environment.hs
- test/Hadolint/Config/EnvironmentSpec.hs
Renamed the configuration variable from `HADOLINT_{ALLOWED => TRUSTED}_REGISTRIES` in order to match the documented behaviour.
Closes #756.
Just changed the relevant variable string values.
Didn't update any of the procedure names, since they still seem correct; they are still handling the list of allowed registries.
Run:
```
HADOLINT_TRUSTED_REGISTRIES=good.example.com hadolint /dev/stdin <<< 'FROM bad.example.org/image:v1.0'
```
Expected output:
```
/dev/stdin:1 DL3026 error: Use only an allowed registry in the FROM image
```
> Bring env var for trusted registries in sync with docs (#756)

- src/Hadolint/Rule/DL3038.hs
- src/Hadolint/Rule/DL3040.hs
- src/Hadolint/Rule/DL3041.hs
- src/Hadolint/Shell.hs
- test/Hadolint/Rule/DL3038Spec.hs
- test/Hadolint/Rule/DL3040Spec.hs
- test/Hadolint/Rule/DL3041Spec.hs
Added so all rules concerning dnf (DL3038, DL3040, DL3041) works analogously for [microdnf](https://github.com/rpm-software-management/microdnf) as well, which closes #742. Note that I have not updated any documentation for the corresponding rule changes, since I wasn't sure if and how this should be done.
Added utility function `cmdsHaveArgs :: [Text.Text] -> [Text.Text] -> Command -> Bool` in `Shell.hs`, which is a generalized version of the function `cmdHasArgs`. The function has been used to check for the rules concerned in this PR.
Test cases have been added so running the tests should be good enough. One can also run hadolint with the following file:
```Dockerfile
FROM centos:1.0    
RUN microdnf install test-1.0.0 && microdnf clean all # Missing -y flag    
RUN microdnf install -y …
```
> DL3038, DL3040, DL3041: Add support for microdnf

- README.md
- src/Hadolint/Rule/DL3026.hs
- test/Hadolint/Rule/DL3026Spec.hs
Add support for trusted registry domain wildcards. Private registries like
Artifactory use sub-domain for Docker registries so this will allow users to
allow any repository under a single domain (`--trusted-registry "*.megacorp.com"`).
Refs #630
Modified DL3026 isAllowed to search the registries set for entries that are either prefixed or suffixed with "*". For those
entries the item is matched as a suffix or prefix respectively. 
This is my very first attempt at Haskell, so please let me know if there is a better way to go about it.
Tests have been added to `DL3026Spec` tho validate the matching rules.
> DL3026: Trusted registries wildcard domains

- .pre-commit-hooks.yaml
Did run hadolint-docker via pre-commit.
By using a public Github Action runner, which failed due to dockerhub rate limits.
Updating the .pre-commit-hooks.yaml to use the ghcr.io hosted public hadolint image, which is not rate limited.
> Switch to non-rate limited ghcr.io hosted container for pre-commit

- docs/INTEGRATION.md
Add [Super-Linter](https://github.com/github/super-linter) to "Code Review" section in docs.
I use Super-Linter in most of my projects and it's awesome. Check out [this podcast by Bret Fisher](https://podcast.bretfisher.com/episodes/lint-everything-with-super-linter) to learn more about it. People should be aware that it includes hadolint.
Update the `docs/INTEGRATION.md` file.
Review the updated docs.
> Add Super-Linter to Code Review docs

- hadolint.cabal
- package.yaml
Removed the second redundant `PatternSynonyms` default extension in package.yaml.
> Remove duplicate extension

- README.md
- src/Hadolint/Config/Environment.hs
- test/Hadolint/Config/EnvironmentSpec.hs
- Decide whether to print ANSI color codes or not based on the
_presence_, not the value of the NO_COLOR environment variable
The specification provided by https://no-color.org regarding the
interpretation of the NO_COLOR environment variable specifically state
that the value does not matter, only whether it is set or not should
change program behavior.
Therefore, Hadolint should respect that and ignore the value.
Assuming no other settings are in place, `NO_COLOR= hadolint Dockerfile` should result in uncolored output just like `NO_COLOR=true hadolint Dockerfile` and `NO_COLOR=n hadolint Dockerfile`. However `unset NO_COLOR; hadolint Dockerfile` should give colored output.
> config: respect NO_COLOR specification

- README.md
- Fix wrong information about the behavior of the `--failure-threshold`
option.
- Add instructions on how to build Hadolint against modified libraries
to the development section.
Since https://github.com/hadolint/hadolint/pull/653 , Hadolint has
treated the failure threshold set by the `--failure-threshold` option as
inclusive and this has been reflected in the `--help` message text. But
the readme has never been updated.
fixes: #788
- The readme now contains the same information as the `--help` text
> documentation: fix and update readme

- docker/Dockerfile
Fixes https://github.com/hadolint/hadolint/issues/792
Fixed the Docker build.
Installed `libtinfo-dev`. I pinned it at `6.*`. Not sure if that's wise, but it feels semver-safe.
`docker build -f docker/Dockerfile .` now completes successfully.
> Add libtinfo-dev

- src/Hadolint/Rule/DL3061.hs
- test/Hadolint/Rule/DL3061Spec.hs
- Fix false positive error DL3061 when encountering a pragma before a
`FROM` instruction.
In particular `# syntax = docker/dockerfile...` but also `# shell = ...`
pragmas can appear before the first `FROM` instruction without error.
fixes: #795
This should no longer produce false positive error DL3061 messages:
```Dockerfile
FROM node:16-alpine3.13 AS builder
WORKDIR /app
COPY ./package*.json ./
```
Thanks to @aaronfi-procore and @subodhdharma for reporting this issue.
> DL3061: fix false positive on pragmas

- README.md
- hadolint.cabal
- src/Hadolint/Config/Commandline.hs
- src/Hadolint/Formatter.hs
- src/Hadolint/Formatter/Format.hs
- src/Hadolint/Formatter/Gnu.hs
- test/Hadolint/Formatter/GnuSpec.hs
Add a GNU style formatter to Hadolint.
This formatter enhances Hadolints ability to produce output for
consumption by other programs, notably the integration with Emacs will
become easier. GNU style error messages are
described here: https://www.gnu.org/prep/standards/html_node/Errors.html
This formatter differs in three ways from the default TTY output format:
- the GNU style has an additional colon after the line number
- the GNU style has no color output
- the GNU style includes the name of the program (`hadolint`) in the
output, since Hadolint is not an interactive program
Adding a new formatter instead of modifying the existing TTY
formatter avoids breaking backwards compatibility. Since the differences
only matters when consuming Hadolint's output with another program,
configuring …
> formatters: Add GNU style formatter

- src/Hadolint/Rule/DL3022.hs
- test/Hadolint/Rule/DL3022Spec.hs
According to discussion in #197 I've tried to provide improvement for DL3022. I don't know if it works, info below.
Tried to implement @lorenzo'a [suggestion](https://github.com/hadolint/hadolint/issues/197#issuecomment-1084586639) :wink: 
Blindfoldly :laughing: 
Probably `stack test`. I couldn't verify it because I coudn't get it to work:
```
$ stack test
(...)
hspec-core> [40 of 40] Compiling Test.Hspec.Core.Runner
hspec-core> /usr/bin/ld.gold: error: cannot find -ltinfo
hspec-core> collect2: error: ld returned 1 exit status
hspec-core> `gcc' failed in phase `Linker'. (Exit code: 1)
Progress 1/4
--  While building package hspec-core-2.9.4 (scroll up to its section to see the error) using:
/home/codito/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.1.0_ghc-8.10.7 …
```
> DL3022 support for copying from images

- .pre-commit-hooks.yaml
eliminating inconsistency. e.g. for version 2.10.0, pre-commit hooks points to outdated version https://github.com/hadolint/hadolint/blob/47e3022493cb0d51e5af21ee346d4b25bc02bfcd/.pre-commit-hooks.yaml#L7
unpinning the version from the docker hook, behaves in the same manner as the native hook.
this is not the best approach, since each version will pull the latest docker image but will also run on the latest version that is installed on the operating system. the best way to handle the issue is to pin the exact version with each release.
set `.pre-commit-config.yaml` as follows
```yaml
- repo: https://github.com/hadolint/hadolint
rev: 23b2b76fe7b757658019ca4e080efa208784621b
hooks:
- id: hadolint-docker
```
then execute pre-commit and see whether the latest docker images has been pulled …
> unpin docker version in pre-commit hook

- src/Hadolint/Config/Configuration.hs
- test/Hadolint/Config/ConfigfileSpec.hs
Make Hadolint read the desired output format from the key `format` in
the config file, instead of `output-format`. This is more convenient,
consistent with the command line options and consistent with the
documentation.
fixes: #775
> bugfix: config file key for output format

- src/Hadolint/Rule/DL3049.hs
- test/Hadolint/Rule/DL3049Spec.hs
- Fix DL3049 behaviour with multistage builds
In a multistage build, when a stage has an alias, it is reasonable to
assume that it will not be the last stage in the build process. Rather
there will be another stage inheriting or copying from that stage.
Therefore required labels don't necessarily need to be present in the
stage with the alias.
fixes: #758
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>
> DL3049: Fix behaviour with multistage builds

- src/Hadolint/Rule/DL3057.hs
- test/Hadolint/Rule/DL3057Spec.hs
DL3057 checks that images produced in multistage builds have a
healthcheck (if the rule is enabled). But if one stage already has the
healthcheck instruction, the other stages should not trigger a warning.
If the stage comes earlier, it's obviously not used as a build result,
therefore doesn't need a healthcheck instruction on its own.
If the stage comes later, it will inherit the healthcheck instruction
from the stage that has it.
This fix works because when a healthcheck is found in a build stage,
that stage is marked as good, but also all stages it inherited from are
also marked as good. Only stages that don't inherit the healthcheck
instruction remain marked as bad, if they don't have the instruction
themselves. Therefore Dockerfiles, which produce multiple images are
also considered. …
> DL3057: fix multiple warnings for multistage builds

- src/Hadolint/Rule/DL3013.hs
- test/Hadolint/Rule/DL3013Spec.hs
- Fix false positive when installing package with other supported VCS
such as: `pip install bzr+ssh://..@1.0.0`, as described in
https://pip.pypa.io/en/stable/topics/vcs-support/.
- Fix false positive when installing package from local directory:
`pip install my/install/path`
- Fix false positive when installing package from http/https url:
`pip install https://foo.bar/baz-1.0.0.zip`
fixes #389
Extended the previous check for a `git+https` vcs scheme to allow any of the supported vcs sources, such as `git+ssh` and `bzr+ssh`, documented in https://pip.pypa.io/en/stable/topics/vcs-support/. Also added passing check if a package source included a forward slash (/) but is not a valid vcs source.
Compare the supported VCS in this PR from the VCS supported from the pip documentation …
> DL3013: Fix false positives for VCS, http and local path packages (#389)

- test/Hadolint/Rule/DL3026Spec.hs
Fixed a typo in DL3026Spec.hs
Swapped two characters
Read DL3026Spec.hs
> bugfix: typo in DL3026Spec.hs

- README.md
The Haskell Platform is deprecated since 2022 and is no longer the recommended way of installing Haskell. For the latest recommended way to install Haskell please see the Downloads page.
> docs: update link to Haskell

- .github/workflows/release.yml
Create and release sha256 checksums for binary releases.
fixes: #856
> release: create checksums for release artifacts

- src/Hadolint/Rule/DL3047.hs
> Missing space in DL3047

- src/Hadolint/Rule/DL3032.hs
- src/Hadolint/Rule/DL3040.hs
- test/Hadolint/Rule/DL3032Spec.hs
- test/Hadolint/Rule/DL3040Spec.hs
Update DL3032 and DL3040 to allow explicit yum cache clean up after install.
Fixes #796
Update DL3032 and DL3040 to allow explicit yum cache clean up after install using `rm -rf /var/cache/yum/*`
Added `||` condition to clean up rules.
Unit tests have been added for both rules.
> Allow rm yum cache clean up

- README.md
- src/Hadolint/Pragma.hs
- src/Hadolint/Process.hs
- test/Hadolint/PragmaSpec.hs
Add global variant of the ignore pragma. This allows users to disable rules for the whole dockerfile by using a pragma like:
```dockerfile
```
- add file-global variant of the ignore pragma
- clean up the pragma parsing code
The file global ignore pragma works almost like the inline ignore pragma. The difference is that it parses into just a set of rules to ignore instead of a map from line-numbers to sets of rules to ignore. Consequently there is no check for line numbers when deciding if a check-failure should be ignored or propagated, all that matters is if that failures code is in that global set of rule codes to ignore.
The following Dockerfile should not trigger any of the globally ignored rules, but will still trigger all other rules just normal:
```Dockerfile
FROM alpine
USER root …
```
> feature: global ignore pragma

- src/Hadolint/Rule/DL3029.hs
- test/Hadolint/Rule/DL3029Spec.hs
Closes #861
Allowed `BUILDPLATFORM` and `TARGETPLATFORM` in `FROM --plaform=`
Updated the existing rule to check if the value contains one of the variables. This is the lazy way without getting into complex regex.
I added new tests, but I have not been able to run anything. I tried to use `nix-shell` to get a development environment, but the compilation is never ending. This is also my first time touching Haskell code, so I barely understand a quarter of the changes I made :sweat_smile:
> fix(DL3029): allow BUILDPLATFORM and TARGETPLATFORM variables

- README.md
Use cabal-install instead of stack in the readme, since stack support was removed along with stack.yaml configuration.
fixes: #899
Signed-off-by: Moritz Röhrich <moritz@ildefons.de>
> docs: use cabal instead of stack in readme

- .gitignore
- hadolint.cabal
- package.yaml
- src/Hadolint/Rule/DL3011.hs
- test/Hadolint/Rule/DL3011Spec.hs
Fix up usage of the AST in DL3011 corresponding to the changes to the AST with respect to port ranges in `EXPOSE` instructions.
requires: https://github.com/hadolint/language-docker/pull/85
fixes: https://github.com/hadolint/hadolint/issues/876
> DL3011: fixup changes in AST

- src/Hadolint/Rule/DL3022.hs
- test/Hadolint/Rule/DL3022Spec.hs
Simple patch to fix bug with hadolint raising false positives if the stages are mentioned by index rather than names.
Such as,
```dockerfile
FROM X as stage1
RUN # do some work, likely, build something to copy
FROM Y as stage2
COPY --from=0 bar .
```
I use decimal conversion over string to get the index and compare it to the count of the stages in source, not sure if there was a better way to write the code I just wrote it because I needed it to be fixed.
Added a couple tests to `DL3022Spec.hs`
> fix: false positive in `DL3022`

- contrib/hadolint.json
I updated the json schema for the hadolint.yaml file
I was creating a hadolint yaml in vscode when I saw it highlighted some keys as non supported.  So I added them to the hadolint.json file.
using a jsonschema validator, such as https://check-jsonschema.readthedocs.io/en/latest/install.html
```
pip install check-jsonschema
yq /path/to/.hadolint.yaml -o json > .hadolint.json
check-jsonschema --schemafile contrib/hadolint.json .hadolint.json
```
> update hadolint's config json schema to support latest properties

- src/Hadolint/Rule/DL3014.hs
- src/Hadolint/Shell.hs
- test/Hadolint/Rule/DL3014Spec.hs
`apt-get` can take the `--quiet` or `-q` argument to increase its quietness level. At the maximum of 2, this will also imply `assume-yes` i.e. the `-y` flag. Therefore if the necessary quietness level has been configured by command line parameters, DL3014 should not alert the user to the missing `-y` flag.
fixes: #911
Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>
Unittests are included. In any case, the following Dockerfile should no longer produce warning DL3014:
```Dockerfile
FROM debian:stable-slim
RUN apt-get update && apt-get install --quiet --quiet sl
```
> DL3014: Fix false positive on double quiet

- src/Hadolint/Rule/DL3028.hs
- test/Hadolint/Rule/DL3028Spec.hs
In Hadolint, there are several gem install flag patterns that result in false positives.
Warnings should not be displayed for the following patterns:
```dockerfile
RUN gem install bundler:2.0.1 -- --use-system-libraries true
RUN gem install bundler:2.0.1 --use-system-libraries true
RUN gem install bundler:2.0.1 --use-system-libraries=true
```
In this PR, I have made adjustments so that these patterns can also be parsed correctly.
I modified the processing to remove options and their subsequent arguments from the list of arguments.
I have added tests related to the additional patterns.
> Improve parsing of gem install flag patterns to reduce false positives

- src/Hadolint/Rule/DL3006.hs
- test/Hadolint/Rule/DL3006Spec.hs
ensure we don't raise if image name is an arg
names can't start with `$`
added a test, which fails if changes not present
> fix: fp in `DL3006`

- src/Hadolint/Shell.hs
This check is related to SC1090 which is already skipped in PR #344 and background in issue #343.
Add SC1091 to list of shellcheck entries to ignore.
Because SC1090 and SC1091 are essentially the same and SC1090 is already excluded.
Simple addition to existing list.
Use this `Dockerfile`
```dockerfile
FROM alpine:3
RUN . /etc/sysconfig/somefile
```
before
```sh
$ hadolint Dockerfile
Dockerfile:2 SC1091 info: Not following: File not included in mock.
```
after
```sh
~/.local/bin/hadolint Dockerfile ; echo $?
0
```
> Ignore unsatisfiable shellcheck error 1091

- src/Hadolint/Rule/DL3009.hs
- test/Hadolint/Rule/DL3009Spec.hs
Improved DL3009 rule to properly handle all apt-based package managers:
- Added support for apt and aptitude in hasUpdate function
- Updated error message to be more specific about tools and path
1. Enhanced the hasUpdate function to detect update operations from apt and aptitude commands
2. Updated the error message to clearly specify which package managers it applies to and the exact path that needs cleaning
Create a test Dockerfile with different apt-based package managers:
```dockerfile
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y python3
RUN apt update && apt install -y curl
RUN aptitude update && aptitude install -y wget
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
```
Run hadolint on the file:
```bash
hadolint Dockerfile
```
The first …
> Improve DL3009 rule to properly handle all apt-based package managers

- .gitignore
- src/Hadolint/Rule/DL3033.hs
- src/Hadolint/Rule/DL3041.hs
- test/Hadolint/Rule/DL3033Spec.hs
- test/Hadolint/Rule/DL3041Spec.hs
In Fedora, RHEL and similar distributions, packages may have an epoch prefixed to their version. This is an integer separated by a colon from the actual version number. The epoch is used to make all packages sortable, regardless of whether the upstream project uses sortable version identifiers.
To deal with this, in Hadolint we must accept that a dnf or yum package may contain a colon in their version number.
related-to: hadolint/hadolint#1117
> DL3041, DL3033: Handle RPM package epoch

- .github/workflows/release.yml
- hadolint.cabal
Split MacOS and Windows releases because Windows should be built without `-fPIC`.
Remove `-fPIC` from Windows builds
related-to: hadolint/hadolint#1126
> fixup release workflow
