src/Formatter.hs, src/Parser.hs, src/Rules.hs, src/Syntax.hs
Hi @lukasmartinelli,
I'm an engineer at Code Climate & am interested in picking away at some of the features Hadolint would need to make implementing #20 easier: I think Hadolint would be a great engine for our platform.
I'm starting with a small fix for #9, so that the source file name can be carried along with the check information & displayed in the output.
=> Display Dockerfile path with results

src/Hadolint/Rules.hs, test/Spec.hs
According to #36.
@hsmade Can you check the regression tests in `test/Spec.hs` whether that is correct like that?
=> Fix pip pinning

src/Hadolint/Rules.hs, test/Spec.hs
@hsmade More suggestions for archive files?
=> Add more archive types #34

src/Hadolint/Parser.hs, src/Hadolint/Syntax.hs, test/Spec.hs
Let me know if I missed something. This is basically the first haskell I've written
=> Add support for parsing SHELL instruction

src/Hadolint/Rules.hs
Add common file compression suffixes for ADD rule
=> Issue 68: Add supported file suffixes for DL3020

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adding new templates for issues and pull requests to get more specific information for troubleshooting issue and faster understanding what is PR about.
=> Add issue and pull request template for GitHub

README.md
For those unfamiliar with Haskell and wondering what to do after `stack build` (includes me to a degree!).
=> Add stack install command to README for local install

README.md, docker/README.md, docs/INTEGRATION.md
- Added the latest release version and downloads badge
- Rephrased _static build_ in the Install section of README
- Rephrased Develop section of README
- Updated docker hub README to use real versions
- Added Integrations documentation for Travis and text editors
=> Hadolint integrations + documentation update

.hindent.yaml, .travis.yml, app/Main.hs, src/Hadolint/Bash.hs, src/Hadolint/Formatter.hs, src/Hadolint/Rules.hs, test/Spec.hs
- ETA reduction & improved laziness
- Linted with _hindent_ to improve readability and unify formatting
```yaml
indent-size: 4
line-length: 100
force-trailing-newline: true
```
_hindent_
=> Lint haskell files using _hindent_

app/Main.hs, package.yaml, src/Hadolint/Formatter.hs, src/Hadolint/Rules.hs, stack.yaml, test/Spec.hs
This meant that of the Check rules had to be removed, as they now are parse errors
Fixes https://github.com/hadolint/hadolint/issues/146
Fixes https://github.com/hadolint/hadolint/issues/76
Fixes https://github.com/hadolint/hadolint/issues/53
Fixes https://github.com/hadolint/hadolint/issues/38
=> Upgrade language-docker to version 2.0

README.md, app/Main.hs, package.yaml
CLI options take precedence over the config file
Closes #118
=> Added support for a config file

src/Hadolint/Rules.hs, test/Spec.hs
=> Added check to ensure the last argument to COPY ends with slash

src/Hadolint/Rules.hs, test/Spec.hs
It had an incorrect handling of pip flags
Fixes #157
=> Fixed pip version pinned check

src/Hadolint/Rules.hs, test/Spec.hs
=> Improve dl3006

package.yaml, src/Hadolint/Rules.hs, stack.yaml, test/Spec.hs
=> Fixed FROM when specifying a registry

README.md, src/Hadolint/Rules.hs, test/Spec.hs
=> Added ability to ignore rules using comments in the dockerfile

src/Hadolint/Rules.hs, test/Spec.hs
fixes #167
If an intermediate image is not used as the FROM clause downstream, then there is no point in having the warning for that stage.
Added plenty new tests for this case
=> Fixed DL3009 when using in intermediate stages

docs/INTEGRATION.md
- Add VS Code extension to the `INTEGRATION.md`
- By adding the text 🙂
=> add vscode integration

app/Main.hs, package.yaml, src/Hadolint/Formatter/Checkstyle.hs, src/Hadolint/Formatter/Codeclimate.hs, src/Hadolint/Formatter/Format.hs, src/Hadolint/Formatter/Json.hs, src/Hadolint/Formatter/TTY.hs, src/Hadolint/Rules.hs, stack.yaml, test/Spec.hs
Additionally added more strinct compiler checks and fixed them.
resolves #192
=> Upgraded parser version

.travis.yml, app/Main.hs, package.yaml, src/Hadolint/Formatter/Checkstyle.hs, src/Hadolint/Formatter/Codeclimate.hs, src/Hadolint/Formatter/Format.hs, src/Hadolint/Formatter/Json.hs, src/Hadolint/Formatter/TTY.hs, src/Hadolint/Rules.hs, stack.yaml, test/Spec.hs
Uses the latest version of language-docker
fixes #203
=> Upgrading the parser to version 6

README.md, package.yaml, src/Hadolint/Rules.hs, test/Spec.hs
=> Warn on plain text arguments for CMD and ENTRYPOINT

src/Hadolint/Bash.hs, src/Hadolint/Rules.hs, test/Spec.hs
* Passing ARG and ENV as variables to the script, fixes #87 
* Using the detected SHELL as the start of the script, fixes #226
=> More improvements to the shellcheck rule

README.md, package.yaml, src/Hadolint/Bash.hs, src/Hadolint/Rules.hs, src/Hadolint/Shell.hs, test/Spec.hs
* Fixed #234 
* Renamed the `Bash` module to `Shell`
* Added notes in the readme about `DL3026`
=> General cleanup

package.yaml, stack.yaml, test/Spec.hs
=> Fixed false positive due to spaces

package.yaml, src/Hadolint/Rules.hs, test/Spec.hs
The test had incorrect assertions, which made the implementation to also be incorrect.
Fixes #184
=> Fix last user root

README.md
hadolint can trigger it so might as well link to it :)
=> Add link to SC2155

README.md, app/Main.hs, package.yaml
This allows users to pass a custom confuguration file path.
closes #242
=> Added a --config flag

src/Hadolint/Rules.hs, test/Spec.hs
=> Fixed false positive with npm run install

.travis.yml, stack.yaml
With 8.6 almost being marked stable, I think it is time to stop using 8.2
=> Compiling with GHC 8.4

src/Hadolint/Rules.hs, test/Spec.hs
=> Fixes false positive in DL3014

app/Main.hs, package.yaml, src/Hadolint.hs, src/Hadolint/Config.hs, src/Hadolint/Lint.hs
Hey,
Following issue #265, I've refactored the code to make the lint function and LintOptions data structure available for files other than the main.
To do this I also had to move functions they depended on to another file.
Tell me if you think something needs to be redone.
Epic Code Reviews
=> Refactor Main

docs/INTEGRATION.md
=> docs/INTEGRATION.md: Added Drone CI section.

docs/INTEGRATION.md
added steps for codeship pro integration
[http://codeship.com/](url)
=> [docs] added Codeship Pro integration

docs/INTEGRATION.md
Add demonstration of how to integrate with GitHub Actions.
=> Updated INTEGRATION.md with GitHub Actions

README.md
Add a lint rule to the readme.
With VSCode
Follow the link to show it.
=> Add missing SC2039 to rules

src/Hadolint/Rules.hs
Moved guards forward as `hlint` was suggesting.
`stack test`
=> Implement hlint suggestions

.travis.yml, package.yaml, stack.yaml, test/Spec.hs
=> Fixed error with comments ending with backslash

.travis.yml
update travis.yml to use addons
travis build
=> use travis homebrew addon

src/Hadolint/Rules.hs, test/Spec.hs
added code to recognize `-o APT::Install-Recommends=false`
fixes #299
=> Fixed false negative for DL3015

.travis.yml, package.yaml, stack.yaml
=> Upgraded parser

docs/INTEGRATION.md
add a snippet for linting your dockerfiles to a jenkinsfile
=> Add Jenkinsfile declarative pipeline step

docs/INTEGRATION.md
* Removed top-level "Automated Code Review" heading
* Corrected a typo and consistent new line between integrations
=> Include Bitbucket Pipelines configuration example

package.yaml, src/Hadolint/Config.hs, src/Hadolint/Rules.hs, stack.yaml, test/ConfigSpec.hs, test/Spec.hs
fixes #332 
fixes #325 
fixes #322 
Additionally, change the YAML package for one implemented in pure Haskell. This will help me play with compiling hadolint to javascript
=> Multiple fixes

src/Hadolint/Rules.hs, src/Hadolint/Shell.hs
While this is probably not noticeable when running the hadolint binary,
it halves the time when executing it as a javascript program, which is
something I'm experimenting with.
=> Improved performance for checking shell related rules

docs/INTEGRATION.md
Added example of how to configure hadolint for drone version 1.0 or later
=> add drone 1.0 example

docs/INTEGRATION.md
Add an example on how to integrate hadolint with CircleCI
Writing the doc with the current orb example
-
=> add circleci integration example

src/Hadolint/Rules.hs, test/Spec.hs
=> Fixed wget or curl rule reporting errors on too many lines

docs/INTEGRATION.md
Added jenkin's k8s plugin example in integrations docs
=> added jenkins' k8s plugin example

docs/INTEGRATION.md, package.yaml
for 1.17.4 because of `alpine` image
=> Bump version

src/Hadolint/Rules.hs, test/Spec.hs
Fixed #376.
Added all `pip` parameters with value to list of ignored for checking of version.
I have also added tests.
=> Fix ignoring pip parameters with value

README.md, docs/INTEGRATION.md
- Categorize integrations by CI and Code Review
- Add integration listing to `README.md` to increase visibility, why? <https://twitter.com/goldbergyoni/status/1227936470322819074>
disclaimer: I wrote the vs code integration.
=> docs: improve integration listing

src/Hadolint/Rules.hs, test/Spec.hs
Fixes #408
I added `-X` option to drop-target list of `apkAddPackages` rule
There is a dedicated test in "apk add rules"
=> Support for apk add -X option

package.yaml, src/Hadolint/Config.hs, src/Hadolint/Formatter/Format.hs, src/Hadolint/Shell.hs, stack.yaml, test/ConfigSpec.hs
Update to stackage lts-15.3
Update in stack.yaml, then fix everything that was broken.
Package builds
=> Use lts-15.3

package.yaml, stack.yaml
=> Upgrading parser to 9.1

README.md, src/Hadolint/Rules.hs, test/Spec.hs
@lorenzo ,
Added new rule **DL3029** to check **--platform** flag in `FROM`. 
Modified README.md and Rules.hs.
Closes #429.
Please review and provide feedback.
=> Added new rule DL3029 to check platform flag in FROM

src/Hadolint/Rules.hs
Travis build is currently failing; fixed as per linting suggestions.
=> Fix travis build failures

src/Hadolint/Rules.hs, test/Spec.hs
=> Fixup python3 -m pip install

README.md, package.yaml, stack.yaml, test/Spec.hs
=> Bumping language-docker to latest version

app/Main.hs, hie.yaml, src/Hadolint.hs, src/Hadolint/Config.hs, src/Hadolint/Formatter/Checkstyle.hs, src/Hadolint/Formatter/Codacy.hs, src/Hadolint/Formatter/Codeclimate.hs, src/Hadolint/Formatter/Format.hs, src/Hadolint/Formatter/Json.hs, src/Hadolint/Formatter/TTY.hs, src/Hadolint/Lint.hs, src/Hadolint/Rules.hs, src/Hadolint/Shell.hs, test/ConfigSpec.hs, test/Spec.hs
Ormolu is the more modern alternative for formatting Haskell files. While it changes our current style entirely, it is more future-proof
=> Reformat with ormolu

docs/INTEGRATION.md
I added a link to [Mega-Linter](https://nvuillam.github.io/mega-linter) in the list of Code Review Tools
By updating MD file :)
Read the readme file :)
=> Add Mega-Linter in "Code Review tools" sections

src/Hadolint/Config.hs
For some reason, compiling Hadolint.Config with optimizations enabled
was taking a long time.
I decided to rewrite the function that I found to be the culprit while
hopefully making it easier to read.
=> Lower compilation times

.github/workflows/haskell.yml
The currently used GitHub action is abandoned, use the official one
=> Use haskell/actions instead of deprecated setup-haskell

hadolint.cabal, package.yaml, src/Hadolint/Formatter/Json.hs
It was outputting an array per file instead of combining them all
fixes #588
=> fixed json formatting

hadolint.cabal, package.yaml, stack.yaml
Bump language-docker version to 9.2.0
fixes: #444
=> dependencies: language-docker version bump to 9.2.0

hadolint.cabal, package.yaml, src/Hadolint/Rule/DL3010.hs, src/Hadolint/Rule/DL3020.hs, src/Hadolint/Rule/DL3021.hs, src/Hadolint/Rule/DL3022.hs, src/Hadolint/Rule/DL3023.hs, src/Hadolint/Rule/DL3045.hs, stack.yaml
Upgraded parser version 
fixes #609
=> Add support for chmod flag

docs/RELEASE.md
Updated the docs to reflect the necessity of updating a config file.
=> Add .pre-commit-hooks.yaml update step to RELEASE.md

README.md
=> Add Podman example + Improve writing

README.md, test/Hadolint/Config/EnvironmentSpec.hs
Make sure HADOLINT_DISABLE_IGNORE_PRAGMA is unset after tests.
Add documentation for HADOLINT_REQUIRE_LABELS env var
=> minor updates to environment variables

contrib/hadolint.json
This avoid an error in IDE when updating .hadolint.yml config file
=> Add SC3046 in hadolint JSON Schema

docs/INTEGRATION.md
Pinned a version of hadolint to the pre-commit config
Found the latest non beta tag in the hadolint repo
$ pre-commit install
=> Update INTEGRATION.md steps for pre-commit

README.md
Add new section for Ignoring Rules in README. This will greatly help with readability and quickly finding all configs related to ignoring rules in one place.
=> docs: Add new section for Ignoring Rules in README

README.md
Added Table of Contents for README
=> docs: Add Table of Contents for README

src/Hadolint/Rule/DL3060.hs
```
RUN yarn install
```
On the other hand, this does not have yarn cache clean but is still okay because the cache will not be included in the final image and removing the cache defeats the purpose of using the cache mount.
```
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn/v6 yarn install
```
I added `RunFlags` to the check.  I checked whether the RunMount contains any CacheMounts.
The second `RUN` line above should not raise DL3060.
=> DL3060 should be suppressed if cache mounts are used

README.md
Update TOC with Ignoring Rules section
=> docs: Update TOC with Ignoring Rules section

docker/Dockerfile
Match casing between FROM and AS statements to address warnings when making a release.
Refs:
- https://github.com/hadolint/hadolint/actions/runs/14010622727/job/39230204603#step:7:212
=> Fix casing in Dockerfile

.github/workflows/haskell.yml, .github/workflows/release.yml, hadolint.cabal
Fix release pipeline:
- only create draft release, so it can be reviewed before being published
- fix path for github checkout action v5
Add dependency package version bounds to satisfy Hackage package versioning policy
=> Release v2.13.1
